@generated
{
  "aliases_explicit.py": [
    "Line 69: Expected 1 errors",
    "Line 70: Expected 1 errors",
    "Line 71: Expected 1 errors",
    "Line 84: Expected 1 errors",
    "Line 86: Expected 1 errors",
    "Line 90: Expected 1 errors",
    "Line 27: Unexpected errors [\"Expected `GoodTypeAlias13` to be a type alias, got Literal['int | str']\"]",
    "Line 28: Unexpected errors [\"untype, got Literal['int | str']\"]",
    "Line 29: Unexpected errors ['Invalid literal expression']",
    "Line 38: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[GoodTypeAlias6, type[tuple[int, int, TypeVar[S], TypeVar[T]]]]\"]",
    "Line 41: Unexpected errors ['untype, got list[type[str]]']",
    "Line 53: Unexpected errors ['assert_type(list[str] | tuple[TypeVar[T], ...], list[str] | tuple[str, ...]) failed']",
    "Line 54: Unexpected errors ['assert_type(Any, tuple[int, int, int, str]) failed']",
    "Line 57: Unexpected errors ['assert_type((int, ParamSpec(ParamSpec[P])) -> Any, (int, str, str) -> None) failed']",
    "Line 60: Unexpected errors ['assert_type((ParamSpec(ParamSpec[P])) -> None, (...) -> None) failed']",
    "Line 61: Unexpected errors ['assert_type(Any, int | str) failed']",
    "Line 62: Unexpected errors ['assert_type(list[Any], list[int | str]) failed']",
    "Line 63: Unexpected errors ['Invalid literal expression']",
    "Line 97: Unexpected errors ['Expected 1 more positional argument']",
    "Line 98: Unexpected errors ['assert_type(list[Any], list[str]) failed']"
  ],
  "aliases_implicit.py": [
    "Line 78: Expected 1 errors",
    "Line 79: Expected 1 errors",
    "Line 80: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 113: Expected 1 errors",
    "Line 117: Expected 1 errors",
    "Line 14: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[Vector, type[Iterable[tuple[TypeVar[TFloat], TypeVar[TFloat]]]]]\"]",
    "Line 18: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[Vector, type[Iterable[tuple[TypeVar[TFloat], TypeVar[TFloat]]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[Vector, type[Iterable[tuple[TypeVar[TFloat], TypeVar[TFloat]]]]]\"]",
    "Line 51: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GoodTypeAlias6, type[tuple[int, int, TypeVar[S], TypeVar[T]]]]\"]",
    "Line 54: Unexpected errors ['untype, got list[type[str]]']",
    "Line 64: Unexpected errors ['assert_type(list[str] | tuple[TypeVar[T], ...], list[str] | tuple[str, ...]) failed']",
    "Line 65: Unexpected errors ['assert_type(Any, tuple[int, int, int, str]) failed']",
    "Line 68: Unexpected errors ['assert_type((int, ParamSpec(ParamSpec[P])) -> Any, (int, str, str) -> None) failed']",
    "Line 72: Unexpected errors ['assert_type((ParamSpec(ParamSpec[P])) -> None, (...) -> None) failed']",
    "Line 89: Unexpected errors ['Expected 5 more positional arguments']",
    "Line 92: Unexpected errors ['Expected 1 more positional argument']",
    "Line 95: Unexpected errors ['EXPECTED Literal[0] <: slice[Error, Error, Error]']",
    "Line 127: Unexpected errors ['Expected 1 more positional argument']",
    "Line 130: Unexpected errors ['Expected 1 more positional argument']"
  ],
  "aliases_newtype.py": [
    "Line 32: Expected 1 errors",
    "Line 44: Expected 1 errors",
    "Line 47: Expected 1 errors",
    "Line 49: Expected 1 errors",
    "Line 51: Expected 1 errors",
    "Line 58: Expected 1 errors",
    "Line 62: Expected 1 errors",
    "Line 13: Unexpected errors ['untype, got NewType', 'EXPECTED Literal[42] <: Args[?_]']",
    "Line 15: Unexpected errors ['assert_type(Any, int) failed', 'EXPECTED Literal[5] <: Args[?_]']"
  ],
  "aliases_recursive.py": [
    "Line 19: Expected 1 errors",
    "Line 20: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 39: Expected 1 errors",
    "Line 50: Expected 1 errors",
    "Line 51: Expected 1 errors",
    "Line 52: Expected 1 errors",
    "Line 72: Expected 1 errors",
    "Line 75: Expected 1 errors",
    "Line 14: Unexpected errors [\"untype, got Literal['Json']\", \"untype, got Literal['Json']\"]",
    "Line 24: Unexpected errors [\"untype, got Literal['Json2']\", \"untype, got Literal['Json2']\"]",
    "Line 30: Unexpected errors [\"untype, got Literal['RecursiveTuple']\"]",
    "Line 42: Unexpected errors [\"untype, got Literal['RecursiveMapping']\"]",
    "Line 58: Unexpected errors ['Object of class `str` has no attribute `__or__`']",
    "Line 59: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GenericTypeAlias1, type[list[Error]]]\"]",
    "Line 62: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GenericTypeAlias1, type[list[Error]]]\"]",
    "Line 65: Unexpected errors ['Object of class `str` has no attribute `__or__`']",
    "Line 67: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GenericTypeAlias2, type[list[Error]]]\"]",
    "Line 68: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GenericTypeAlias2, type[list[Error]]]\"]"
  ],
  "aliases_type_statement.py": [
    "Line 26: Expected 1 errors",
    "Line 42: Expected 1 errors",
    "Line 44: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 52: Expected 1 errors",
    "Line 58: Expected 1 errors",
    "Line 79: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 84: Expected 1 errors",
    "Line 86: Expected 1 errors",
    "Line 90: Expected 1 errors",
    "Line 9: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 21: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 22: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 82: Unexpected errors ['untype, got list[type[int] | type[str]]']"
  ],
  "aliases_typealiastype.py": [
    "Line 44: Expected 1 errors",
    "Line 46: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 53: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 56: Expected 1 errors",
    "Line 57: Expected 1 errors",
    "Line 59: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 61: Expected 1 errors",
    "Line 62: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 64: Expected 1 errors",
    "Line 17: Unexpected errors ['EXPECTED tuple[type[TypeVar[T]]] <: tuple[ParamSpec | TypeVar | TypeVarTuple, ...]']",
    "Line 18: Unexpected errors ['EXPECTED tuple[type[TypeVar[S]], type[TypeVar[T]]] <: tuple[ParamSpec | TypeVar | TypeVarTuple, ...]']",
    "Line 19: Unexpected errors ['EXPECTED tuple[type[TypeVar[T]]] <: tuple[ParamSpec | TypeVar | TypeVarTuple, ...]']",
    "Line 22: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 23: Unexpected errors ['EXPECTED tuple[type[TypeVar[S]], type[TypeVar[TStr]], type[ParamSpec[P]], type[TypeVarTuple[Ts]]] <: tuple[ParamSpec | TypeVar | TypeVarTuple, ...]']",
    "Line 30: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 31: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 35: Unexpected errors ['untype, got GenericAlias']",
    "Line 36: Unexpected errors ['untype, got GenericAlias']",
    "Line 37: Unexpected errors ['untype, got GenericAlias']",
    "Line 38: Unexpected errors ['untype, got GenericAlias']",
    "Line 39: Unexpected errors ['untype, got GenericAlias', 'TODO: Starred(ExprStarred - Answers::expr_infer']"
  ],
  "aliases_variance.py": [
    "Line 24: Expected 1 errors",
    "Line 28: Expected 1 errors",
    "Line 44: Expected 1 errors"
  ],
  "annotations_coroutines.py": [],
  "annotations_forward_refs.py": [
    "Line 22: Expected 1 errors",
    "Line 23: Expected 1 errors",
    "Line 24: Expected 1 errors",
    "Line 25: Expected 1 errors",
    "Line 46: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 53: Expected 1 errors",
    "Line 66: Expected 1 errors",
    "Line 87: Unexpected errors ['untype, got (self: ClassD) -> None']",
    "Line 96: Unexpected errors ['assert_type(Any, int) failed']"
  ],
  "annotations_generators.py": [
    "Line 51: Expected 1 errors",
    "Line 86: Expected 1 errors",
    "Line 91: Expected 1 errors",
    "Line 56: Unexpected errors ['EXPECTED None <: C']",
    "Line 101: Unexpected errors ['Yield expression found but the function has an incompatible annotation `IntIterator`']",
    "Line 110: Unexpected errors ['Yield expression found but the function has an incompatible annotation `AsyncIntIterator`']",
    "Line 127: Unexpected errors ['EXPECTED Generator[None, float, None] <: Generator[None, int, None]']",
    "Line 131: Unexpected errors ['EXPECTED int <: float']",
    "Line 145: Unexpected errors ['Yield expression found but the function has an incompatible annotation `AsyncIterable[str]`']",
    "Line 149: Unexpected errors ['EXPECTED list[int] <: Generator[int, None, None]']",
    "Line 150: Unexpected errors ['EXPECTED list[int] <: Generator[int, None, None]']",
    "Line 154: Unexpected errors [\"Missing argument 'result'\", 'EXPECTED Literal[1] <: float']",
    "Line 160: Unexpected errors [\"Missing argument 'result'\", 'EXPECTED Literal[1] <: float']",
    "Line 161: Unexpected errors ['Yield expression found but the function has an incompatible annotation `AsyncGenerator[str, None]`']",
    "Line 167: Unexpected errors ['assert_type(Coroutine[Any, Any, AsyncGenerator[str, None]], AsyncGenerator[str, None]) failed']",
    "Line 168: Unexpected errors ['EXPECTED Coroutine[Unknown, Unknown, AsyncGenerator[str, None]] <: AsyncGenerator[str, None]']",
    "Line 174: Unexpected errors ['assert_type(Coroutine[Any, Any, AsyncGenerator[str, None]], AsyncGenerator[str, None]) failed']",
    "Line 175: Unexpected errors ['EXPECTED Coroutine[Unknown, Unknown, AsyncGenerator[str, None]] <: AsyncIterator[str]']",
    "Line 179: Unexpected errors ['EXPECTED None <: AsyncIterator[int]']",
    "Line 187: Unexpected errors ['Yield expression found but the function has an incompatible annotation `AsyncIterator[int]`']",
    "Line 190: Unexpected errors ['assert_type(() -> Coroutine[Any, Any, AsyncIterator[int]], () -> AsyncIterator[int]) failed']"
  ],
  "annotations_methods.py": [
    "Line 19: Unexpected errors ['Expected a callable, got type[?_]']",
    "Line 21: Unexpected errors ['EXPECTED Forall[T, (val: type[T]) -> T] <: (ParamSpec(@_)) -> @_']",
    "Line 23: Unexpected errors ['Expected a callable, got type[?_]']",
    "Line 31: Unexpected errors ['assert_type(Any, A) failed', 'Expected a callable, got classmethod[Forall[T, (cls: type[T]) -> T]]']",
    "Line 36: Unexpected errors ['assert_type(Any, B) failed', 'Expected a callable, got classmethod[Forall[T, (cls: type[T]) -> T]]']",
    "Line 48: Unexpected errors ['assert_type(Any, A) failed', 'EXPECTED type[A] <: Args[?_]']",
    "Line 49: Unexpected errors ['assert_type(Any, B) failed', 'EXPECTED type[B] <: Args[?_]']",
    "Line 50: Unexpected errors ['assert_type(Any, B) failed', 'EXPECTED type[B] <: Args[?_]']",
    "Line 51: Unexpected errors ['assert_type(Any, A) failed', 'EXPECTED type[A] <: Args[?_]']"
  ],
  "annotations_typeexpr.py": [
    "Line 93: Expected 1 errors",
    "Line 95: Expected 1 errors",
    "Line 100: Expected 1 errors",
    "Line 26: Unexpected errors [\"EXPECTED Literal['Monty'] <: Buffer\"]",
    "Line 77: Unexpected errors ['assert_type(tuple[Any], tuple[Any, ...]) failed']"
  ],
  "callables_annotation.py": [
    "Line 56: Expected 1 errors",
    "Line 59: Expected 1 errors",
    "Line 159: Expected 1 errors",
    "Line 51: Unexpected errors ['assert_type(int, tuple[int, ...]) failed']",
    "Line 52: Unexpected errors ['assert_type(int, dict[str, int]) failed']",
    "Line 90: Unexpected errors ['EXPECTED (x: int) -> str <: (int, ParamSpec(Ellipsis)) -> str']",
    "Line 92: Unexpected errors ['EXPECTED (a: int, b: int, c: int) -> str <: (int, ParamSpec(Ellipsis)) -> str']",
    "Line 147: Unexpected errors ['EXPECTED Proto1 <: (...) -> None']",
    "Line 148: Unexpected errors ['EXPECTED (...) -> None <: Proto1']",
    "Line 149: Unexpected errors ['EXPECTED Proto5[Any] <: (...) -> None']",
    "Line 150: Unexpected errors ['EXPECTED (...) -> None <: Proto5[Any]']",
    "Line 151: Unexpected errors ['EXPECTED Proto2 <: (int, ParamSpec(Ellipsis)) -> None']",
    "Line 152: Unexpected errors ['EXPECTED (int, ParamSpec(Ellipsis)) -> None <: Proto2']",
    "Line 153: Unexpected errors ['EXPECTED Proto3 <: (...) -> None']",
    "Line 154: Unexpected errors ['EXPECTED (...) -> None <: Proto3']",
    "Line 171: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[Callback1, type[(ParamSpec(ParamSpec[P])) -> str]]\"]",
    "Line 174: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[Callback1, type[(ParamSpec(ParamSpec[P])) -> str]]\"]",
    "Line 175: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[Callback2, type[(int, ParamSpec(ParamSpec[P])) -> str]]\"]",
    "Line 186: Unexpected errors ['EXPECTED (int, str) -> str <: (int, ParamSpec(Ellipsis)) -> str']",
    "Line 188: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[CallbackWithInt, type[(int, ParamSpec(ParamSpec[P])) -> str]]\"]"
  ],
  "callables_kwargs.py": [
    "Line 46: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 122: Expected 1 errors",
    "Line 23: Unexpected errors [\"Can't apply arguments to non-class, got Unpack[TypedDict[TD2]]\"]",
    "Line 24: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 31: Unexpected errors [\"Can't apply arguments to non-class, got Unpack[TypedDict[TD2]]\"]",
    "Line 32: Unexpected errors ['assert_type(Any, str) failed']",
    "Line 34: Unexpected errors [\"Can't apply arguments to non-class, got Unpack[TypedDict[TD2]]\"]",
    "Line 35: Unexpected errors ['assert_type(Any, str) failed']",
    "Line 41: Unexpected errors ['assert_type(Unpack[TypedDict[TD1]], TypedDict[TD1]) failed']",
    "Line 47: Unexpected errors ['EXPECTED Literal[1] <: Unpack[TypedDict[TD2]]', \"EXPECTED Literal[''] <: Unpack[TypedDict[TD2]]\", \"EXPECTED Literal['5'] <: Unpack[TypedDict[TD2]]\"]",
    "Line 50: Unexpected errors ['Expected argument after ** to be a mapping, got: TypedDict[TD2]']",
    "Line 62: Unexpected errors [\"Missing argument 'v3'\", 'Expected argument after ** to be a mapping, got: TypedDict[TD2]']",
    "Line 99: Unexpected errors ['EXPECTED (**Unpack[TypedDict[TD2]]) -> None <: TDProtocol1']",
    "Line 100: Unexpected errors ['EXPECTED (**Unpack[TypedDict[TD2]]) -> None <: TDProtocol2']",
    "Line 104: Unexpected errors ['EXPECTED (**Unpack[TypedDict[TD2]]) -> None <: TDProtocol6']"
  ],
  "callables_protocol.py": [
    "Line 186: Expected 1 errors",
    "Line 187: Expected 1 errors",
    "Line 34: Unexpected errors ['EXPECTED (*bytes, *, max_len: int | None) -> list[bytes] <: Proto1']",
    "Line 65: Unexpected errors ['EXPECTED (*bytes, **str) -> None <: Proto2']",
    "Line 78: Unexpected errors ['EXPECTED (*bytes, **str) -> None <: Proto3']",
    "Line 79: Unexpected errors ['EXPECTED (*bytes) -> None <: Proto3']",
    "Line 80: Unexpected errors ['EXPECTED (*str, **str) -> None <: Proto3']",
    "Line 81: Unexpected errors ['EXPECTED (*bytes, **bytes) -> None <: Proto3']",
    "Line 82: Unexpected errors ['EXPECTED (**str) -> None <: Proto3']",
    "Line 109: Unexpected errors ['EXPECTED (a: int, b: str) -> int <: Proto5']",
    "Line 168: Unexpected errors ['EXPECTED (x: Any) -> Any <: Proto8']",
    "Line 191: Unexpected errors ['EXPECTED (x: int) -> str <: (ParamSpec(@_)) -> str']",
    "Line 196: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 199: Unexpected errors ['EXPECTED Literal[3] <: Kwargs[?_]']",
    "Line 216: Unexpected errors ['EXPECTED () -> None <: Proto10']",
    "Line 236: Unexpected errors ['EXPECTED (int, y: str, z: None) -> Any <: Proto11']",
    "Line 237: Unexpected errors ['EXPECTED (x: int, y: str, z: None) -> Any <: Proto11']",
    "Line 258: Unexpected errors ['EXPECTED (*Any, *, kwarg0: Any, kwarg1: Any) -> None <: Proto12']",
    "Line 259: Unexpected errors ['EXPECTED (*Any, **Any) -> None <: Proto12']",
    "Line 283: Unexpected errors ['EXPECTED (path: str) -> str <: Proto13_Default']",
    "Line 286: Unexpected errors ['EXPECTED (path: str) -> str <: Proto13_NoDefault']",
    "Line 287: Unexpected errors ['EXPECTED (path: str) -> str <: Proto13_NoDefault']",
    "Line 310: Unexpected errors ['EXPECTED (*, path: str) -> str <: Proto14_Default']",
    "Line 312: Unexpected errors ['EXPECTED (*, path: str) -> str <: Proto14_NoDefault']",
    "Line 313: Unexpected errors ['EXPECTED (*, path: str) -> str <: Proto14_NoDefault']"
  ],
  "callables_subtyping.py": [
    "Line 51: Expected 1 errors",
    "Line 52: Expected 1 errors",
    "Line 55: Expected 1 errors",
    "Line 58: Expected 1 errors",
    "Line 82: Expected 1 errors",
    "Line 85: Expected 1 errors",
    "Line 86: Expected 1 errors",
    "Line 116: Expected 1 errors",
    "Line 119: Expected 1 errors",
    "Line 120: Expected 1 errors",
    "Line 122: Expected 1 errors",
    "Line 124: Expected 1 errors",
    "Line 125: Expected 1 errors",
    "Line 126: Expected 1 errors",
    "Line 151: Expected 1 errors",
    "Line 154: Expected 1 errors",
    "Line 155: Expected 1 errors",
    "Line 187: Expected 1 errors",
    "Line 190: Expected 1 errors",
    "Line 191: Expected 1 errors",
    "Line 193: Expected 1 errors",
    "Line 195: Expected 1 errors",
    "Line 196: Expected 1 errors",
    "Line 197: Expected 1 errors",
    "Line 236: Expected 1 errors",
    "Line 237: Expected 1 errors",
    "Line 240: Expected 1 errors",
    "Line 243: Expected 1 errors",
    "Line 273: Expected 1 errors",
    "Line 297: Expected 1 errors",
    "Line 20: Unexpected errors ['EXPECTED (float) -> int <: (int) -> float']",
    "Line 21: Unexpected errors ['EXPECTED (float) -> float <: (int) -> float']",
    "Line 22: Unexpected errors ['EXPECTED (int) -> int <: (int) -> float']",
    "Line 24: Unexpected errors ['EXPECTED (float) -> int <: (float) -> float']",
    "Line 28: Unexpected errors ['EXPECTED (float) -> int <: (int) -> int']",
    "Line 211: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[TypeAliasWithP, type[(ParamSpec(ParamSpec[P])) -> None]]\"]",
    "Line 213: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[TypeAliasWithP, type[(ParamSpec(ParamSpec[P])) -> None]]\"]"
  ],
  "classes_classvar.py": [
    "Line 45: Expected 1 errors",
    "Line 46: Expected 1 errors",
    "Line 47: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 64: Expected 1 errors",
    "Line 67: Expected 1 errors",
    "Line 71: Expected 1 errors",
    "Line 105: Expected 1 errors",
    "Line 61: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `ClassVar[list[int]]`']",
    "Line 146: Unexpected errors ['EXPECTED () -> None <: (ParamSpec(@_)) -> None']"
  ],
  "classes_override.py": [
    "Line 53: Expected 1 errors",
    "Line 79: Expected 1 errors",
    "Line 84: Expected 1 errors",
    "Line 89: Expected 1 errors",
    "Lines 56, 65: Expected error (tag 'method4')",
    "Line 77: Unexpected errors ['EXPECTED () -> int <: (ParamSpec(@_)) -> int']"
  ],
  "constructors_call_init.py": [
    "Line 42: Expected 1 errors",
    "Line 107: Expected 1 errors",
    "Line 20: Unexpected errors ['EXPECTED Literal[1] <: float']",
    "Line 72: Unexpected errors ['assert_type(Class5[Any], Class5[list[int]]) failed']",
    "Line 74: Unexpected errors ['assert_type(Class5[Any], Class5[set[str]]) failed']",
    "Line 75: Unexpected errors ['assert_type(Class5[Any], Class5[float]) failed']",
    "Line 91: Unexpected errors ['assert_type(Class6[TypeVar[V1], TypeVar[V2]], Class6[int, str]) failed']",
    "Line 92: Unexpected errors ['EXPECTED Class6[int, str] <: Class6[TypeVar[V1], TypeVar[V2]]']",
    "Line 99: Unexpected errors ['assert_type(Class7[TypeVar[V2], TypeVar[V1]], Class7[str, int]) failed']",
    "Line 100: Unexpected errors ['EXPECTED Class7[str, int] <: Class7[TypeVar[V2], TypeVar[V1]]']"
  ],
  "constructors_call_metaclass.py": [
    "Line 15: Unexpected errors ['EXPECTED None <: NoReturn']",
    "Line 20: Unexpected errors ['EXPECTED object <: Class1', 'Expected 0 positional arguments, got 1']",
    "Line 23: Unexpected errors ['assert_type(Class1, NoReturn) failed', \"Missing argument 'x'\"]",
    "Line 33: Unexpected errors ['EXPECTED object <: Class2', 'Expected 0 positional arguments, got 1']",
    "Line 43: Unexpected errors ['Object of class `super` has no attribute `__call__`']",
    "Line 48: Unexpected errors ['EXPECTED object <: Class3', 'Expected 0 positional arguments, got 1']",
    "Line 57: Unexpected errors ['Object of class `super` has no attribute `__call__`']",
    "Line 62: Unexpected errors ['EXPECTED object <: Class4', 'Expected 0 positional arguments, got 1']"
  ],
  "constructors_call_new.py": [
    "Line 16: Unexpected errors ['EXPECTED object <: Class1[?_]', 'Expected 0 positional arguments, got 1']",
    "Line 20: Unexpected errors ['EXPECTED Literal[1] <: float']",
    "Line 29: Unexpected errors ['EXPECTED object <: Class2[?_]', 'Expected 0 positional arguments, got 1']",
    "Line 64: Unexpected errors ['assert_type(Class4, Class4 | Any) failed', \"Missing argument 'x'\"]",
    "Line 69: Unexpected errors ['EXPECTED None <: NoReturn']",
    "Line 76: Unexpected errors ['assert_type(Class5, NoReturn) failed', \"Missing argument 'x'\"]",
    "Line 98: Unexpected errors ['Expected 0 positional arguments, got 1', 'Expected argument after ** to be a mapping, got: Unknown']",
    "Line 104: Unexpected errors ['assert_type(object, Class7) failed']"
  ],
  "constructors_call_type.py": [
    "Line 25: Unexpected errors ['EXPECTED object <: Class1', 'Expected argument after ** to be a mapping, got: Unknown']",
    "Line 35: Unexpected errors ['EXPECTED object <: Class2', 'Expected 0 positional arguments, got 1']",
    "Line 63: Unexpected errors ['Expected a callable, got type[?_]']",
    "Line 71: Unexpected errors ['Expected a callable, got type[?_]']",
    "Line 79: Unexpected errors ['Expected a callable, got type[?_]']",
    "Line 80: Unexpected errors ['Expected a callable, got type[?_]']"
  ],
  "constructors_callable.py": [
    "Line 35: Unexpected errors ['EXPECTED type[Class1] <: (ParamSpec(@_)) -> @_']",
    "Line 36: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 37: Unexpected errors ['assert_type(Any, Class1) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 48: Unexpected errors ['EXPECTED type[Class2] <: (ParamSpec(@_)) -> @_']",
    "Line 49: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 50: Unexpected errors ['assert_type(Any, Class2) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 62: Unexpected errors ['EXPECTED type[Class3] <: (ParamSpec(@_)) -> @_']",
    "Line 63: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 64: Unexpected errors ['assert_type(Any, Class3) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 76: Unexpected errors ['EXPECTED type[Class4] <: (ParamSpec(@_)) -> @_']",
    "Line 77: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 78: Unexpected errors ['assert_type(Any, int) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 85: Unexpected errors ['EXPECTED None <: NoReturn']",
    "Line 93: Unexpected errors ['EXPECTED object <: Class5', 'Expected 0 positional arguments, got 1']",
    "Line 96: Unexpected errors ['EXPECTED type[Class5] <: (ParamSpec(@_)) -> @_']",
    "Line 97: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 100: Unexpected errors ['assert_type(Any, NoReturn) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 105: Unexpected errors ['assert_type(Any, NoReturn) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 124: Unexpected errors ['EXPECTED type[Class6] <: (ParamSpec(@_)) -> @_']",
    "Line 125: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 126: Unexpected errors ['assert_type(Any, Class6Proxy) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 134: Unexpected errors ['Expected 0 positional arguments, got 1']",
    "Line 141: Unexpected errors ['EXPECTED type[Class6Any] <: (ParamSpec(@_)) -> @_']",
    "Line 142: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 143: Unexpected errors ['Answers::expr_infer wrong number of arguments to call']",
    "Line 160: Unexpected errors ['EXPECTED type[Class7] <: (ParamSpec(@_)) -> @_']",
    "Line 161: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 164: Unexpected errors ['assert_type(Any, Class7[int]) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 165: Unexpected errors ['assert_type(Any, Class7[str]) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 178: Unexpected errors ['EXPECTED object <: Class8[?_]', 'Expected 0 positional arguments, got 1']",
    "Line 181: Unexpected errors ['EXPECTED type[Class8] <: (ParamSpec(@_)) -> @_']",
    "Line 182: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 183: Unexpected errors ['assert_type(Any, Class8[str]) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 192: Unexpected errors ['EXPECTED type[Class9] <: (ParamSpec(@_)) -> @_']",
    "Line 193: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 194: Unexpected errors ['assert_type(Any, Class9) failed', 'Answers::expr_infer wrong number of arguments to call']"
  ],
  "constructors_consistency.py": [
    "Line 22: Unexpected errors ['EXPECTED object <: Class1', 'Expected 0 positional arguments, got 1']"
  ],
  "dataclasses_descriptors.py": [
    "Line 35: Unexpected errors ['Expected 0 positional arguments, got 1']",
    "Line 37: Unexpected errors ['assert_type(Desc1, int) failed']",
    "Line 61: Unexpected errors ['assert_type(Any, list[int]) failed', 'Instance-only attribute `x` of class `DC2` is not visible on the class']",
    "Line 62: Unexpected errors ['assert_type(Any, list[str]) failed', 'Instance-only attribute `y` of class `DC2` is not visible on the class']",
    "Line 63: Unexpected errors ['assert_type(Desc2[str], list[str]) failed']",
    "Line 65: Unexpected errors ['Expected 0 positional arguments, got 3']",
    "Line 66: Unexpected errors ['assert_type(Desc2[int], int) failed']",
    "Line 67: Unexpected errors ['assert_type(Desc2[str], str) failed']",
    "Line 68: Unexpected errors ['assert_type(Desc2[str], str) failed']"
  ],
  "dataclasses_final.py": [
    "Line 27: Expected 1 errors",
    "Line 35: Expected 1 errors",
    "Line 36: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 30: Unexpected errors [\"Unexpected keyword argument 'final_no_default'\", \"Unexpected keyword argument 'final_with_default'\"]"
  ],
  "dataclasses_frozen.py": [
    "Line 17: Expected 1 errors",
    "Lines 22, 23: Expected error (tag 'DC2')",
    "Lines 32, 33: Expected error (tag 'DC4')",
    "Line 14: Unexpected errors ['Expected 0 positional arguments, got 2']"
  ],
  "dataclasses_hash.py": [
    "Line 23: Unexpected errors ['Expected 0 positional arguments, got 1']",
    "Line 40: Unexpected errors ['Expected 0 positional arguments, got 1']",
    "Line 48: Unexpected errors ['Expected 0 positional arguments, got 1']",
    "Line 59: Unexpected errors ['Expected 0 positional arguments, got 1']",
    "Line 70: Unexpected errors ['Expected 0 positional arguments, got 1']"
  ],
  "dataclasses_inheritance.py": [
    "Line 60: Expected 1 errors",
    "Line 64: Expected 1 errors",
    "Line 23: Unexpected errors ['Expected 0 positional arguments, got 2']",
    "Line 37: Unexpected errors ['EXPECTED Literal[15] <: float']",
    "Line 40: Unexpected errors ['Expected 0 positional arguments, got 3']"
  ],
  "dataclasses_kwonly.py": [
    "Line 17: Unexpected errors ['Expected 0 positional arguments, got 1']",
    "Line 18: Unexpected errors [\"Unexpected keyword argument 'a'\"]",
    "Line 19: Unexpected errors [\"Unexpected keyword argument 'a'\", \"Unexpected keyword argument 'b'\"]",
    "Line 20: Unexpected errors ['Expected 0 positional arguments, got 1', \"Unexpected keyword argument 'b'\"]",
    "Line 28: Unexpected errors ['EXPECTED Literal[3] <: _MISSING_TYPE']",
    "Line 32: Unexpected errors ['Expected 0 positional arguments, got 1']",
    "Line 33: Unexpected errors [\"Unexpected keyword argument 'a'\"]",
    "Line 34: Unexpected errors [\"Unexpected keyword argument 'a'\", \"Unexpected keyword argument 'b'\"]",
    "Line 35: Unexpected errors ['Expected 0 positional arguments, got 1', \"Unexpected keyword argument 'b'\"]",
    "Line 47: Unexpected errors ['Expected 0 positional arguments, got 1']",
    "Line 48: Unexpected errors [\"Unexpected keyword argument 'a'\"]",
    "Line 49: Unexpected errors [\"Unexpected keyword argument 'a'\", \"Unexpected keyword argument 'b'\"]",
    "Line 50: Unexpected errors ['Expected 0 positional arguments, got 1', \"Unexpected keyword argument 'b'\"]",
    "Line 61: Unexpected errors ['Expected 0 positional arguments, got 2', \"Unexpected keyword argument 'b'\"]",
    "Line 62: Unexpected errors [\"Unexpected keyword argument 'a'\", \"Unexpected keyword argument 'b'\", \"Unexpected keyword argument 'c'\"]"
  ],
  "dataclasses_order.py": [
    "Line 50: Expected 1 errors",
    "Line 19: Unexpected errors ['Expected 0 positional arguments, got 2']",
    "Line 20: Unexpected errors ['Expected 0 positional arguments, got 2']",
    "Line 46: Unexpected errors ['Expected 0 positional arguments, got 2']"
  ],
  "dataclasses_postinit.py": [
    "Line 19: Expected 1 errors",
    "Line 36: Expected 1 errors",
    "Line 23: Unexpected errors ['Expected 0 positional arguments, got 5']"
  ],
  "dataclasses_slots.py": [
    "Line 25: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Lines 10, 11: Expected error (tag 'DC1')",
    "Line 48: Unexpected errors ['Expected 0 positional arguments, got 2']",
    "Line 56: Unexpected errors ['Class `DC5` has no class attribute `__slots__`']",
    "Line 57: Unexpected errors ['Object of class `DC5` has no attribute `__slots__`', 'Expected 0 positional arguments, got 1']"
  ],
  "dataclasses_transform_class.py": [
    "Line 51: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 72: Expected 1 errors",
    "Line 122: Expected 1 errors",
    "Line 60: Unexpected errors [\"Missing argument 'not_a_field'\", \"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\", \"Unexpected keyword argument 'other_name'\"]",
    "Line 68: Unexpected errors [\"Missing argument 'not_a_field'\", \"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]",
    "Line 74: Unexpected errors [\"Missing argument 'not_a_field'\", \"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]",
    "Line 76: Unexpected errors [\"Missing argument 'not_a_field'\", \"Unexpected keyword argument 'id'\"]",
    "Line 106: Unexpected errors [\"Unexpected keyword argument 'id'\"]",
    "Line 119: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]"
  ],
  "dataclasses_transform_converter.py": [
    "Line 118: Expected 1 errors",
    "Line 29: Unexpected errors ['EXPECTED tuple[Forall[S, T, (*, converter: (S) -> T, default: S | None, default_factory: () -> S | None) -> T]] <: tuple[(...) -> Any | type[Any], ...]']",
    "Line 60: Unexpected errors [\"Missing argument 'base'\"]",
    "Line 64: Unexpected errors [\"Missing argument 'base'\"]",
    "Line 68: Unexpected errors [\"Missing argument 'base'\"]",
    "Line 102: Unexpected errors ['EXPECTED type[ConverterClass] <: (@_) -> @_']",
    "Line 103: Unexpected errors ['EXPECTED int | str <: int']",
    "Line 104: Unexpected errors ['EXPECTED type[dict] <: (@_) -> @_']",
    "Line 112: Unexpected errors ['Expected 0 positional arguments, got 5']",
    "Line 114: Unexpected errors [\"EXPECTED Literal['f1'] <: int\"]",
    "Line 115: Unexpected errors [\"EXPECTED Literal['f6'] <: ConverterClass\"]",
    "Line 116: Unexpected errors [\"EXPECTED Literal[b'f6'] <: ConverterClass\"]",
    "Line 121: Unexpected errors ['Expected 0 positional arguments, got 6']",
    "Line 132: Unexpected errors ['EXPECTED type[str] <: () -> str | None']"
  ],
  "dataclasses_transform_field.py": [
    "Line 60: Unexpected errors [\"Unexpected keyword argument 'name'\"]",
    "Line 77: Unexpected errors [\"Unexpected keyword argument 'name'\"]"
  ],
  "dataclasses_transform_func.py": [
    "Line 61: Expected 1 errors",
    "Line 97: Expected 1 errors",
    "Lines 89, 90: Expected error (tag 'Customer3Subclass')",
    "Line 50: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]",
    "Line 53: Unexpected errors ['Expected 0 positional arguments, got 2']",
    "Line 67: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]",
    "Line 94: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]"
  ],
  "dataclasses_transform_meta.py": [
    "Line 51: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 73: Expected 1 errors",
    "Line 103: Expected 1 errors",
    "Line 60: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\", \"Unexpected keyword argument 'other_name'\"]",
    "Line 69: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]",
    "Line 75: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]",
    "Line 77: Unexpected errors [\"Unexpected keyword argument 'id'\"]",
    "Line 100: Unexpected errors [\"Unexpected keyword argument 'id'\", \"Unexpected keyword argument 'name'\"]"
  ],
  "dataclasses_usage.py": [
    "Lines 58, 61: Expected error (tag 'DC1')",
    "Lines 64, 67: Expected error (tag 'DC2')",
    "Lines 70, 73: Expected error (tag 'DC3')",
    "Line 22: Unexpected errors ['EXPECTED int <: float']",
    "Line 25: Unexpected errors ['Expected 0 positional arguments, got 2']",
    "Line 35: Unexpected errors ['EXPECTED BoundMethod[InventoryItem, (self: object) -> None] <: InventoryItemInitProto']",
    "Line 38: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 39: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 40: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 41: Unexpected errors [\"Missing argument 'flush'\", 'Object of class `InventoryItem` has no attribute `__lt__`']",
    "Line 42: Unexpected errors [\"Missing argument 'flush'\", 'Object of class `InventoryItem` has no attribute `__le__`']",
    "Line 43: Unexpected errors [\"Missing argument 'flush'\", 'Object of class `InventoryItem` has no attribute `__gt__`']",
    "Line 44: Unexpected errors [\"Missing argument 'flush'\", 'Object of class `InventoryItem` has no attribute `__ge__`']",
    "Line 66: Unexpected errors ['EXPECTED Literal[1] <: _MISSING_TYPE']",
    "Line 72: Unexpected errors ['EXPECTED Literal[0] <: InitVar[int]']",
    "Line 82: Unexpected errors ['Expected 0 positional arguments, got 1']",
    "Line 92: Unexpected errors [\"Missing argument 'base'\"]",
    "Line 102: Unexpected errors ['Expected 0 positional arguments, got 1']",
    "Line 106: Unexpected errors ['assert_type(BoundMethod[DC6, (str) -> int], (str) -> int) failed']",
    "Line 123: Unexpected errors ['Expected 0 positional arguments, got 1']",
    "Line 135: Unexpected errors [\"EXPECTED Literal['s'] <: _MISSING_TYPE\"]",
    "Line 185: Unexpected errors [\"EXPECTED Literal['hello'] <: _MISSING_TYPE\"]",
    "Line 186: Unexpected errors [\"EXPECTED () -> Literal['hello'] <: _MISSING_TYPE\"]",
    "Line 194: Unexpected errors [\"Unexpected keyword argument 'prop_2'\"]",
    "Line 205: Unexpected errors ['EXPECTED DC15 <: DataclassProto']",
    "Line 213: Unexpected errors ['assert_type(DC16[Any], DC16[int]) failed', 'Expected 0 positional arguments, got 1']",
    "Line 220: Unexpected errors ['Expected 0 positional arguments, got 1']"
  ],
  "directives_assert_type.py": [
    "Line 24: Unexpected errors ['assert_type(ForwardReference, Any) failed', \"untype, got Literal['ForwardReference']\"]"
  ],
  "directives_cast.py": [
    "Line 16: Expected 1 errors",
    "Line 10: Unexpected errors ['Expected 1 more positional argument']"
  ],
  "directives_deprecated.py": [
    "Line 24: Expected 1 errors",
    "Line 30: Expected 1 errors",
    "Line 41: Expected 1 errors",
    "Line 42: Expected 1 errors",
    "Line 44: Expected 1 errors",
    "Line 47: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 58: Expected 1 errors",
    "Line 69: Expected 1 errors",
    "Line 98: Expected 1 errors",
    "Line 19: Unexpected errors ['Could not find import of `_directives_deprecated_library`, Could not find path for `_directives_deprecated_library`']"
  ],
  "directives_no_type_check.py": [],
  "directives_reveal_type.py": [
    "Line 14: Unexpected errors ['revealed type: int | str']",
    "Line 15: Unexpected errors ['revealed type: list[int]']",
    "Line 16: Unexpected errors ['revealed type: Any']",
    "Line 17: Unexpected errors ['revealed type: ForwardReference']"
  ],
  "directives_type_checking.py": [
    "Line 11: Unexpected errors [\"EXPECTED Literal[''] <: int\"]",
    "Line 16: Unexpected errors ['Inconsistent type annotations for b: list[str], list[int]']",
    "Line 18: Unexpected errors ['assert_type(list[int] | list[str], list[int]) failed']"
  ],
  "directives_type_ignore.py": [],
  "directives_type_ignore_file1.py": [
    "Line 16: Unexpected errors [\"EXPECTED Literal[''] <: int\"]"
  ],
  "directives_type_ignore_file2.py": [],
  "directives_version_platform.py": [],
  "enums_behaviors.py": [
    "Line 39: Expected 1 errors",
    "Line 19: Unexpected errors ['EXPECTED EnumMeta <: type[@_]']",
    "Line 20: Unexpected errors ['assert_type(Any, Color) failed']",
    "Line 26: Unexpected errors ['assert_type(type[Color], Color) failed', 'Expected 0 type arguments for class `Color`, got 1.', \"untype, got Literal['RED']\"]",
    "Line 27: Unexpected errors ['assert_type(Enum, Color) failed', 'Expected `__call__` to be a callable, got (cls: EnumMeta, value: str, names: Iterable[Iterable[str | Any]] | Iterable[str] | Mapping[str, Any] | str, *, module: str | None, qualname: str | None, type: type | None, start: int, boundary: FlagBoundary | None) -> type[Enum] | Forall[_EnumMemberT, (cls: type[_EnumMemberT], value: Any, names: None) -> _EnumMemberT] | Forall[_EnumMemberT, (cls: type[_EnumMemberT], value: Any, *Any) -> _EnumMemberT]']"
  ],
  "enums_definition.py": [],
  "enums_expansion.py": [
    "Line 53: Expected 1 errors",
    "Line 23: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 31: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 33: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 50: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 52: Unexpected errors ['assert_type(Literal[CustomFlags.FLAG3], CustomFlags) failed']",
    "Line 63: Unexpected errors ['assert_type(Never, CustomFlags) failed']"
  ],
  "enums_member_names.py": [],
  "enums_member_values.py": [
    "Line 90: Unexpected errors ['Could not find import of `_enums_member_values`, Could not find path for `_enums_member_values`']"
  ],
  "enums_members.py": [
    "Line 82: Expected 1 errors",
    "Line 83: Expected 1 errors",
    "Line 84: Expected 1 errors",
    "Line 85: Expected 1 errors",
    "Line 116: Expected 1 errors",
    "Line 27: Unexpected errors ['assert_type(Any, str) failed', 'Instance-only attribute `genus` of class `Pet` is not visible on the class']",
    "Line 28: Unexpected errors ['assert_type(Any, str) failed', 'Instance-only attribute `species` of class `Pet` is not visible on the class']",
    "Line 33: Unexpected errors ['Could not find import of `_enums_members`, Could not find path for `_enums_members`']",
    "Line 35: Unexpected errors ['assert_type(Any, str) failed']",
    "Line 36: Unexpected errors ['assert_type(Any, str) failed']",
    "Line 37: Unexpected errors ['Literal expression `Pet2` is not an enumeration']",
    "Line 38: Unexpected errors ['Literal expression `Pet2` is not an enumeration']",
    "Line 68: Unexpected errors ['EXPECTED (x: int) -> int <: (ParamSpec(@_)) -> int']",
    "Line 75: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 100: Unexpected errors ['assert_type(Literal[TrafficLight.AMBER], Literal[TrafficLight.YELLOW]) failed']",
    "Line 128: Unexpected errors ['Could not find name `reveal_type`', 'revealed type: Literal[2]']"
  ],
  "exceptions_context_managers.py": [
    "Line 64: Unexpected errors ['assert_type(int | str, str) failed']",
    "Line 71: Unexpected errors ['assert_type(int | str, str) failed']",
    "Line 78: Unexpected errors ['assert_type(int | str, str) failed']",
    "Line 85: Unexpected errors ['assert_type(int | str, str) failed']"
  ],
  "generics_base_class.py": [
    "Line 30: Expected 1 errors",
    "Line 68: Expected 1 errors",
    "Line 45: Unexpected errors ['assert_type(Iterator[Any], Iterator[int]) failed', 'Expected 1 more positional argument', 'EXPECTED LinkedList[int] <: () -> @_']"
  ],
  "generics_basic.py": [
    "Line 49: Expected 1 errors",
    "Line 55: Expected 1 errors",
    "Line 121: Expected 1 errors",
    "Line 191: Expected 1 errors",
    "Line 19: Unexpected errors ['EXPECTED Sequence[?_] <: ?_', 'EXPECTED Literal[0] <: slice[Error, Error, Error]']",
    "Line 34: Unexpected errors ['TODO: Expr::attr_infer attribute base undefined for type: ?_ (trying to access __add__)']",
    "Line 67: Unexpected errors ['assert_type(MyStr, str) failed']",
    "Line 68: Unexpected errors ['assert_type(MyStr, str) failed', 'EXPECTED str <: MyStr']",
    "Line 139: Unexpected errors ['assert_type(Any, int) failed', 'Expected 1 more positional argument']",
    "Line 140: Unexpected errors ['assert_type(Any, int) failed', 'Expected 1 more positional argument']",
    "Line 182: Unexpected errors ['Expected 1 more positional argument', 'EXPECTED MyIterableAny <: () -> @_']"
  ],
  "generics_defaults.py": [
    "Line 104: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 30: Unexpected errors ['assert_type(type[NoNonDefaults[Error, Error]], type[NoNonDefaults[str, int]]) failed']",
    "Line 45: Unexpected errors ['assert_type(type[AllTheDefaults[Error, Error, Error, Error, Error]], type[AllTheDefaults[Any, Any, str, int, bool]]) failed']",
    "Line 76: Unexpected errors ['untype, got ParamSpec']",
    "Line 79: Unexpected errors ['Expected 0 type arguments for class `Class_ParamSpec`, got 2.']",
    "Line 80: Unexpected errors ['Expected 0 type arguments for class `Class_ParamSpec`, got 2.']",
    "Line 81: Unexpected errors ['Expected 0 type arguments for class `Class_ParamSpec`, got 1.', 'untype, got list[type[bool]]', 'Expected 0 type arguments for class `Class_ParamSpec`, got 2.']",
    "Line 91: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 94: Unexpected errors ['Expected 0 type arguments for class `Class_TypeVarTuple`, got 1.', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 95: Unexpected errors ['Expected 0 type arguments for class `Class_TypeVarTuple`, got 2.']",
    "Line 96: Unexpected errors ['Expected 0 type arguments for class `Class_TypeVarTuple`, got 2.', 'Expected 0 type arguments for class `Class_TypeVarTuple`, got 2.']",
    "Line 127: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 148: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'untype, got ParamSpec']",
    "Line 151: Unexpected errors ['Expected 1 type argument for class `Foo6`, got 2.', 'Expected 1 type argument for class `Foo6`, got 3.', 'untype, got list[type[bool] | type[float]]']",
    "Line 152: Unexpected errors ['Expected 1 type argument for class `Foo6`, got 3.', 'untype, got list[type[bytes]]', 'Expected 1 type argument for class `Foo6`, got 3.', 'untype, got list[type[bytes]]']",
    "Line 166: Unexpected errors ['assert_type(Any, (Foo7[int]) -> Foo7[int]) failed', 'Generic attribute `meth` of class `Foo7` is not visible on the class']",
    "Line 167: Unexpected errors ['assert_type(Any, int) failed', 'Generic attribute `attr` of class `Foo7` is not visible on the class']"
  ],
  "generics_defaults_referential.py": [
    "Line 53: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 68: Expected 1 errors",
    "Line 74: Expected 1 errors",
    "Line 78: Expected 1 errors",
    "Line 23: Unexpected errors ['assert_type(type[slice[Error, Error, Error]], type[slice[int, int, int | None]]) failed']",
    "Line 24: Unexpected errors ['assert_type(slice[Any, Any, Any], slice[int, int, int | None]) failed']",
    "Line 25: Unexpected errors ['assert_type(slice[str, TypeVar[StartT], int | None], slice[str, str, int | None]) failed']",
    "Line 94: Unexpected errors ['assert_type(type[Bar[Error, Error]], type[Bar[Any, list[Any]]]) failed']",
    "Line 95: Unexpected errors ['assert_type(type[Bar[int, list[TypeVar[Z1]]]], type[Bar[int, list[int]]]) failed']",
    "Line 96: Unexpected errors ['assert_type(Bar[int, list[TypeVar[Z1]]], Bar[int, list[int]]) failed']"
  ],
  "generics_defaults_specialization.py": [
    "Line 30: Expected 1 errors",
    "Line 25: Unexpected errors ['untype, got Forall[DefaultStrT, LegacyExplicitTypeAlias[MyAlias, type[SomethingWithNoDefaults[int, DefaultStrT]]]]']",
    "Line 26: Unexpected errors ['assert_type(Any, SomethingWithNoDefaults[int, str]) failed']",
    "Line 45: Unexpected errors ['assert_type(type[Bar[Error]], type[Bar[str]]) failed']",
    "Line 46: Unexpected errors ['assert_type(Bar[Any], Bar[str]) failed']"
  ],
  "generics_paramspec_basic.py": [
    "Line 15: Expected 1 errors",
    "Line 23: Expected 1 errors",
    "Line 27: Expected 1 errors",
    "Line 31: Expected 1 errors",
    "Line 35: Expected 1 errors",
    "Line 39: Expected 1 errors"
  ],
  "generics_paramspec_components.py": [
    "Line 17: Expected 1 errors",
    "Line 20: Expected 1 errors",
    "Line 23: Expected 1 errors",
    "Line 26: Expected 1 errors",
    "Line 30: Expected 1 errors",
    "Line 35: Expected 1 errors",
    "Line 36: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 41: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 47: Unexpected errors ['assert_type(Any, int) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 53: Unexpected errors ['EXPECTED (*Args[?_], **Kwargs[?_]) -> None <: (ParamSpec(?_)) -> None']",
    "Line 63: Unexpected errors ['EXPECTED (s: str, *Args[?_], **Kwargs[?_]) -> None <: (str, ParamSpec(?_)) -> None']",
    "Line 68: Unexpected errors ['Answers::expr_infer wrong number of arguments to call']",
    "Line 74: Unexpected errors ['EXPECTED (*Args[?_], **Kwargs[?_]) -> None <: (ParamSpec(?_)) -> None']",
    "Line 79: Unexpected errors ['Answers::expr_infer wrong number of arguments to call']",
    "Line 82: Unexpected errors ['`Args[?_]` is not iterable', 'Expected argument after ** to be a mapping, got: Kwargs[?_]']",
    "Line 85: Unexpected errors ['EXPECTED (*Args[?_], **Kwargs[?_]) -> None <: (ParamSpec(?_)) -> None']",
    "Line 89: Unexpected errors ['Answers::expr_infer wrong number of arguments to call', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 96: Unexpected errors ['EXPECTED (a: int, b: str) -> int <: (ParamSpec(@_)) -> int', 'EXPECTED Literal[1] <: Args[?_]', \"EXPECTED Literal['A'] <: Args[?_]\"]",
    "Line 97: Unexpected errors ['EXPECTED (a: int, b: str) -> int <: (ParamSpec(@_)) -> int', \"EXPECTED Literal['A'] <: Kwargs[?_]\", 'EXPECTED Literal[1] <: Kwargs[?_]']"
  ],
  "generics_paramspec_semantics.py": [
    "Line 21: Unexpected errors ['EXPECTED (str, bool) -> int <: (ParamSpec(@_)) -> int']",
    "Line 22: Unexpected errors ['assert_type((ParamSpec(Any)) -> str, (str, bool) -> str) failed']",
    "Line 24: Unexpected errors ['Answers::expr_infer wrong number of arguments to call']",
    "Line 25: Unexpected errors ['assert_type(Any, str) failed']",
    "Line 42: Unexpected errors ['EXPECTED (x: int, y: str) -> int <: (ParamSpec(@_)) -> int', 'EXPECTED (x: int, y: str) -> int <: (ParamSpec(@_)) -> int']",
    "Line 43: Unexpected errors ['assert_type(Any, bool) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 44: Unexpected errors ['assert_type(Any, bool) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 81: Unexpected errors ['EXPECTED (int) -> str <: (ParamSpec(@_)) -> str']",
    "Line 82: Unexpected errors ['untype, got list[type[int]]']",
    "Line 84: Unexpected errors ['assert_type((ParamSpec(Any)) -> str, (int) -> str) failed']",
    "Line 95: Unexpected errors ['EXPECTED (x: int, *bool) -> int <: (ParamSpec(@_)) -> int']",
    "Line 96: Unexpected errors ['assert_type(Any, bool) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 97: Unexpected errors ['assert_type(Any, bool) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 105: Unexpected errors ['EXPECTED (x: int, *bool) -> int <: (int, ParamSpec(@_)) -> int']",
    "Line 106: Unexpected errors ['assert_type(Any, bool) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 107: Unexpected errors ['assert_type(Any, bool) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 117: Unexpected errors ['EXPECTED (x: int, *bool) -> int <: (int, ParamSpec(@_)) -> int']",
    "Line 118: Unexpected errors ['assert_type(Any, bool) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 119: Unexpected errors ['assert_type(Any, bool) failed', 'Answers::expr_infer wrong number of arguments to call']",
    "Line 142: Unexpected errors ['EXPECTED (*int) -> int <: (int, ParamSpec(@_)) -> int']"
  ],
  "generics_paramspec_specialization.py": [
    "Line 44: Expected 1 errors",
    "Line 32: Unexpected errors ['untype, got list[type[bool] | type[int]]']",
    "Line 40: Unexpected errors ['untype, got list[@_]', 'untype, got list[@_]']",
    "Line 52: Unexpected errors ['untype, got list[type[bool] | type[int] | type[str]]']",
    "Line 53: Unexpected errors ['Answers::expr_infer wrong number of arguments to call']",
    "Line 58: Unexpected errors ['Expected 1 type argument for class `ClassC`, got 3.']",
    "Line 59: Unexpected errors ['Answers::expr_infer wrong number of arguments to call']"
  ],
  "generics_scoping.py": [
    "Line 50: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 75: Expected 1 errors",
    "Line 78: Expected 1 errors",
    "Line 87: Expected 1 errors",
    "Line 94: Expected 1 errors",
    "Line 95: Expected 1 errors"
  ],
  "generics_self_advanced.py": [
    "Line 18: Unexpected errors ['assert_type(property, ParentA) failed']",
    "Line 19: Unexpected errors ['assert_type(property, ChildA) failed']",
    "Line 35: Unexpected errors ['assert_type(ChildB, Self) failed']",
    "Line 37: Unexpected errors ['assert_type(list[Self], Self) failed', 'EXPECTED Literal[0] <: slice[Error, Error, Error]']",
    "Line 38: Unexpected errors ['assert_type(Any, Self) failed', 'Expected a callable, got classmethod[(cls: ParentB) -> ParentB]']",
    "Line 42: Unexpected errors ['assert_type(ChildB, type[Self]) failed']",
    "Line 44: Unexpected errors ['assert_type(list[Self], Self) failed', 'EXPECTED Literal[0] <: slice[Error, Error, Error]']",
    "Line 45: Unexpected errors ['assert_type(Any, Self) failed', 'Expected a callable, got classmethod[(cls: ParentB) -> ParentB]']"
  ],
  "generics_self_attributes.py": [
    "Line 22: Unexpected errors ['EXPECTED int <: Buffer']",
    "Line 29: Unexpected errors ['EXPECTED OrdinalLinkedList <: Self | None', \"Unexpected keyword argument 'value'\", \"Unexpected keyword argument 'next'\"]"
  ],
  "generics_self_basic.py": [
    "Line 20: Expected 1 errors",
    "Line 33: Expected 1 errors",
    "Line 14: Unexpected errors ['assert_type(Shape, Self) failed']",
    "Line 15: Unexpected errors ['Object of class `Shape` has no attribute `scale`']",
    "Line 27: Unexpected errors ['assert_type(Shape, type[Self]) failed']",
    "Line 28: Unexpected errors ['Expected a callable, got Shape']",
    "Line 37: Unexpected errors ['Expected a callable, got Shape']",
    "Line 40: Unexpected errors ['assert_type(Shape, Self) failed']",
    "Line 52: Unexpected errors ['assert_type(Shape, Circle) failed']",
    "Line 54: Unexpected errors ['assert_type(Any, Shape) failed', 'Expected a callable, got classmethod[(cls: Shape, config: dict[str, float]) -> Shape]']",
    "Line 55: Unexpected errors ['assert_type(Any, Circle) failed', 'Expected a callable, got classmethod[(cls: Shape, config: dict[str, float]) -> Shape]']"
  ],
  "generics_self_protocols.py": [
    "Line 61: Expected 1 errors",
    "Line 64: Expected 1 errors"
  ],
  "generics_self_usage.py": [
    "Line 73: Expected 1 errors",
    "Line 76: Expected 1 errors",
    "Line 82: Expected 1 errors",
    "Line 86: Expected 1 errors",
    "Line 101: Expected 1 errors",
    "Line 103: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 116: Expected 1 errors",
    "Line 121: Expected 1 errors",
    "Line 125: Expected 1 errors",
    "Line 15: Unexpected errors ['Expected a callable, got ReturnsSelf']",
    "Line 30: Unexpected errors ['EXPECTED ReturnsSelf <: type[ReturnsSelf]']",
    "Line 50: Unexpected errors ['EXPECTED (self: CallableAttribute) -> int <: (Self) -> int']",
    "Line 59: Unexpected errors [\"Missing argument 'flush'\"]",
    "Line 60: Unexpected errors [\"Missing argument 'flush'\", 'TODO: Expr::attr_infer attribute base undefined for type: Self (trying to access x)']",
    "Line 63: Unexpected errors ['EXPECTED HasNestedFunction <: Self']",
    "Line 93: Unexpected errors ['Object of class `Foo3` has no attribute `child_value`']",
    "Line 109: Unexpected errors ['EXPECTED () -> Base <: (ParamSpec(@_)) -> Base']",
    "Line 114: Unexpected errors ['EXPECTED (foo: Base) -> Base <: (ParamSpec(@_)) -> Base']"
  ],
  "generics_syntax_compatibility.py": [],
  "generics_syntax_declarations.py": [
    "Line 46: Expected 1 errors",
    "Line 62: Expected 1 errors",
    "Line 66: Expected 1 errors",
    "Line 14: Unexpected errors ['assert_type(type[?_], TypeVar) failed']",
    "Line 15: Unexpected errors ['assert_type(type[?_], TypeVarTuple) failed']",
    "Line 16: Unexpected errors ['assert_type(type[?_], ParamSpec) failed']",
    "Line 33: Unexpected errors ['TODO: Expr::attr_infer attribute base undefined for type: ?_ (trying to access capitalize)']"
  ],
  "generics_syntax_infer_variance.py": [
    "Line 28: Unexpected errors ['EXPECTED ShouldBeCovariant1[int] <: ShouldBeCovariant1[float]']",
    "Line 36: Unexpected errors ['EXPECTED ShouldBeCovariant2[int] <: ShouldBeCovariant2[float]']",
    "Line 45: Unexpected errors ['EXPECTED ShouldBeCovariant3[int] <: ShouldBeCovariant3[float]']",
    "Line 54: Unexpected errors ['EXPECTED ShouldBeCovariant4[int] <: ShouldBeCovariant4[float]', 'Expected 0 positional arguments, got 1']",
    "Line 67: Unexpected errors ['EXPECTED ShouldBeCovariant5[int] <: ShouldBeCovariant5[float]']",
    "Line 78: Unexpected errors ['EXPECTED ShouldBeCovariant6[int] <: ShouldBeCovariant6[float]']",
    "Line 90: Unexpected errors ['Could not find name `value`']",
    "Line 149: Unexpected errors ['EXPECTED ShouldBeContravariant1[float] <: ShouldBeContravariant1[int]']"
  ],
  "generics_syntax_scoping.py": [
    "Line 14: Expected 1 errors",
    "Line 92: Expected 1 errors",
    "Line 95: Expected 1 errors",
    "Line 98: Expected 1 errors",
    "Line 52: Unexpected errors [\"Missing argument 'base'\", 'EXPECTED Literal[0] <: bytearray | bytes | str']",
    "Line 61: Unexpected errors ['TODO: StmtNonlocal - Bindings::stmt']",
    "Line 66: Unexpected errors ['TODO: StmtGlobal - Bindings::stmt']",
    "Line 67: Unexpected errors ['assert_type(str, int) failed']",
    "Line 85: Unexpected errors [\"Missing argument 'base'\", 'EXPECTED Literal[0] <: bytearray | bytes | str']",
    "Line 90: Unexpected errors [\"Missing argument 'base'\", 'EXPECTED Literal[1] <: bytearray | bytes | str']",
    "Line 102: Unexpected errors [\"Missing argument 'base'\", 'EXPECTED Literal[0] <: bytearray | bytes | str']",
    "Line 106: Unexpected errors [\"Missing argument 'base'\", 'EXPECTED Literal[1] <: bytearray | bytes | str']",
    "Line 111: Unexpected errors [\"EXPECTED Literal[''] <: Buffer\"]",
    "Line 116: Unexpected errors ['assert_type(int, TypeVar) failed']"
  ],
  "generics_type_erasure.py": [
    "Line 56: Unexpected errors ['assert_type(Any, bytes) failed']"
  ],
  "generics_typevartuple_args.py": [
    "Line 33: Expected 1 errors",
    "Line 34: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 57: Expected 1 errors",
    "Line 58: Expected 1 errors",
    "Line 59: Expected 1 errors",
    "Line 67: Expected 1 errors",
    "Line 76: Expected 1 errors",
    "Line 16: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 20: Unexpected errors ['assert_type(tuple[Any], tuple[int, str]) failed']",
    "Line 27: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 31: Unexpected errors ['assert_type(tuple[Any], tuple[()]) failed']",
    "Line 32: Unexpected errors ['assert_type(tuple[Any], tuple[int, str]) failed']",
    "Line 42: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 51: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 62: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 70: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']"
  ],
  "generics_typevartuple_basic.py": [
    "Line 52: Expected 1 errors",
    "Line 53: Expected 1 errors",
    "Line 56: Expected 1 errors",
    "Line 59: Expected 1 errors",
    "Line 89: Expected 1 errors",
    "Line 99: Expected 1 errors",
    "Line 100: Expected 1 errors",
    "Line 12: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 16: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 23: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 24: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 25: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 27: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 36: Unexpected errors ['Expected 1 type argument for class `Array`, got 2.', 'untype, got NewType', 'untype, got NewType', 'EXPECTED tuple[Unknown, Unknown] <: tuple[Error]', 'EXPECTED Literal[1] <: Args[?_]', 'EXPECTED Literal[2] <: Args[?_]']",
    "Line 37: Unexpected errors ['Expected 1 type argument for class `Array`, got 3.', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'EXPECTED tuple[Unknown, Unknown, Unknown] <: tuple[Error]', 'EXPECTED Literal[1] <: Args[?_]', 'EXPECTED Literal[1] <: Args[?_]', 'EXPECTED Literal[1] <: Args[?_]']",
    "Line 38: Unexpected errors ['Expected 1 type argument for class `Array`, got 4.', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 39: Unexpected errors ['EXPECTED tuple[Unknown, Unknown, Unknown, Unknown] <: tuple[Error]', 'EXPECTED Literal[1] <: Args[?_]', 'EXPECTED Literal[1] <: Args[?_]', 'EXPECTED Literal[1] <: Args[?_]', 'EXPECTED Literal[1] <: Args[?_]']",
    "Line 54: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 75: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 84: Unexpected errors ['assert_type(tuple[Any], tuple[int]) failed']",
    "Line 93: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 97: Unexpected errors ['untype, got NewType', 'untype, got NewType', 'Expected 1 type argument for class `Array`, got 2.', 'untype, got NewType', 'untype, got NewType']"
  ],
  "generics_typevartuple_callable.py": [
    "Line 17: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 25: Unexpected errors ['EXPECTED (arg1: int, arg2: str) -> None <: (Error) -> None', \"EXPECTED tuple[Literal[0], Literal['']] <: tuple[Error]\"]",
    "Line 29: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 41: Unexpected errors ['assert_type(tuple[Any, Any], tuple[str, int, complex]) failed', 'EXPECTED (a: int, b: str, c: int, d: complex) -> tuple[complex, str, int] <: (int, Error, @_) -> tuple[@_, Error]']",
    "Line 42: Unexpected errors ['assert_type(tuple[Any, Any], tuple[str]) failed', 'EXPECTED (a: int, d: str) -> tuple[str] <: (int, Error, @_) -> tuple[@_, Error]']",
    "Line 45: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 49: Unexpected errors ['assert_type(tuple[Any, Any], tuple[float, str, complex]) failed']"
  ],
  "generics_typevartuple_concat.py": [
    "Line 22: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 26: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'Expected 1 type argument for class `Array`, got 2.', 'untype, got NewType', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 30: Unexpected errors ['Expected 1 type argument for class `Array`, got 2.', 'untype, got NewType', 'TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 34: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'Expected 1 type argument for class `Array`, got 3.', 'untype, got NewType', 'TODO: Starred(ExprStarred - Answers::expr_infer', 'untype, got NewType']",
    "Line 38: Unexpected errors ['Expected 1 type argument for class `Array`, got 2.', 'untype, got NewType', 'untype, got NewType']",
    "Line 40: Unexpected errors ['Expected 1 type argument for class `Array`, got 3.', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 42: Unexpected errors ['Expected 1 type argument for class `Array`, got 2.', 'untype, got NewType', 'untype, got NewType']",
    "Line 44: Unexpected errors ['Expected 1 type argument for class `Array`, got 4.', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 47: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 51: Unexpected errors [\"EXPECTED tuple[Literal[True], Literal['a']] <: tuple[Error]\"]",
    "Line 52: Unexpected errors ['assert_type(tuple[int, Any], tuple[int, bool, str]) failed']",
    "Line 55: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 56: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']"
  ],
  "generics_typevartuple_overloads.py": [
    "Line 16: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 18: Unexpected errors ['Expected 1 type argument for class `Array`, got 2.', 'Expected 1 type argument for class `Array`, got 2.']",
    "Line 22: Unexpected errors ['Expected 1 type argument for class `Array`, got 3.', 'Expected 1 type argument for class `Array`, got 3.']",
    "Line 29: Unexpected errors ['Expected 1 type argument for class `Array`, got 2.', 'Expected 1 type argument for class `Array`, got 3.']",
    "Line 30: Unexpected errors ['assert_type(Any, Array[?_]) failed', 'Expected 1 type argument for class `Array`, got 2.']",
    "Line 31: Unexpected errors ['assert_type(Any, Array[?_]) failed', 'Expected 1 type argument for class `Array`, got 3.']"
  ],
  "generics_typevartuple_specialization.py": [
    "Line 16: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 24: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 28: Unexpected errors ['Expected 1 type argument for class `Array`, got 2.', 'untype, got NewType', 'untype, got NewType']",
    "Line 33: Unexpected errors ['Expected 1 type argument for class `Array`, got 3.', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 41: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 42: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 45: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[IntTuple, type[tuple[int, Error]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[NamedArray, type[tuple[str, Array[Error]]]]\"]",
    "Line 46: Unexpected errors ['assert_type(Any, tuple[int, float, bool]) failed']",
    "Line 47: Unexpected errors ['assert_type(Any, tuple[str, Array[Any]]) failed', 'untype, got NewType']",
    "Line 50: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[IntTuple, type[tuple[int, Error]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[NamedArray, type[tuple[str, Array[Error]]]]\"]",
    "Line 51: Unexpected errors ['assert_type(Any, tuple[int]) failed']",
    "Line 52: Unexpected errors ['assert_type(Any, tuple[str, Array[Any]]) failed', 'Expected 1 type argument for class `Array`, got 0.']",
    "Line 59: Unexpected errors ['Class `Array2` uses type variables not specified in `Generic` or `Protocol` base', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 63: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 67: Unexpected errors ['untype, got Forall[DType, LegacyImplicitTypeAlias[Array1D, type[Array2[DType, Any]]]]']",
    "Line 68: Unexpected errors ['assert_type(Any, Array2[Any, Any]) failed']",
    "Line 76: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[FloatArray, type[Array2[float, Error]]]\"]",
    "Line 80: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[FloatArray, type[Array2[float, Error]]]\"]",
    "Line 89: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 92: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[VariadicTuple, type[tuple[TypeVar[T], Error]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[VariadicTuple, type[tuple[TypeVar[T], Error]]]\"]",
    "Line 93: Unexpected errors ['assert_type(Any, tuple[str, int]) failed']",
    "Line 94: Unexpected errors ['assert_type(Any, tuple[float]) failed']",
    "Line 95: Unexpected errors ['assert_type(tuple[TypeVar[T], Any], tuple[Any, Any]) failed', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 101: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 102: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[IntTupleVar, type[tuple[int, Error]]]\"]",
    "Line 103: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[IntTupleVar, type[tuple[int, Error]]]\"]",
    "Line 108: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[IntTupleGeneric, type[tuple[int, TypeVar[T]]]]\"]",
    "Line 117: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 118: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 119: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 120: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 125: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 130: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA7, type[tuple[Error, TypeVar[T1], TypeVar[T2]]]]\", 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 134: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA7, type[tuple[Error, TypeVar[T1], TypeVar[T2]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA7, type[tuple[Error, TypeVar[T1], TypeVar[T2]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA7, type[tuple[Error, TypeVar[T1], TypeVar[T2]]]]\"]",
    "Line 135: Unexpected errors ['assert_type(tuple[tuple[Any], Any, Any], tuple[tuple[()], str, bool]) failed']",
    "Line 136: Unexpected errors ['assert_type(tuple[tuple[Any], Any, Any], tuple[tuple[str], bool, float]) failed']",
    "Line 137: Unexpected errors ['assert_type(tuple[tuple[Any], Any, Any], tuple[tuple[str, bool], float, int]) failed']",
    "Line 140: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 143: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA8, type[tuple[TypeVar[T1], Error, TypeVar[T2], TypeVar[T3]]]]\", 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 147: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA8, type[tuple[TypeVar[T1], Error, TypeVar[T2], TypeVar[T3]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA8, type[tuple[TypeVar[T1], Error, TypeVar[T2], TypeVar[T3]]]]\"]",
    "Line 148: Unexpected errors ['assert_type(tuple[tuple[Any], Any, Any, Any], tuple[tuple[()], str, bool, float]) failed']",
    "Line 149: Unexpected errors ['assert_type(tuple[tuple[Any], Any, Any, Any], tuple[tuple[bool], str, float, int]) failed']",
    "Line 152: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 153: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA9, type[tuple[Error, TypeVar[T1]]]]\"]",
    "Line 156: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA9, type[tuple[Error, TypeVar[T1]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA9, type[tuple[Error, TypeVar[T1]]]]\"]",
    "Line 157: Unexpected errors ['assert_type(Any, tuple[Any, int]) failed', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 158: Unexpected errors ['assert_type(Any, tuple[Any, str]) failed', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 159: Unexpected errors ['assert_type(Any, tuple[Any, str]) failed', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 162: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']"
  ],
  "generics_typevartuple_unpack.py": [
    "Line 30: Expected 1 errors",
    "Line 17: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 21: Unexpected errors ['Expected 1 type argument for class `Array`, got 3.', 'untype, got NewType', 'TODO: Starred(ExprStarred - Answers::expr_infer', 'untype, got NewType']",
    "Line 26: Unexpected errors ['Expected 1 type argument for class `Array`, got 4.', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'Expected 1 type argument for class `Array`, got 2.', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 36: Unexpected errors ['Expected 1 type argument for class `Array`, got 2.', 'untype, got NewType', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 40: Unexpected errors ['Expected 1 type argument for class `Array`, got 4.', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 44: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']"
  ],
  "generics_upper_bound.py": [
    "Line 24: Expected 1 errors",
    "Line 51: Expected 1 errors",
    "Line 31: Unexpected errors ['EXPECTED ?_ <: Sized', 'EXPECTED ?_ <: Sized']"
  ],
  "generics_variance.py": [
    "Line 77: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 93: Expected 1 errors",
    "Line 105: Expected 1 errors",
    "Line 113: Expected 1 errors",
    "Line 163: Expected 1 errors",
    "Line 167: Expected 1 errors",
    "Line 191: Expected 1 errors",
    "Lines 125, 126: Expected error (tag 'CoContra_Child2')",
    "Lines 131, 132: Expected error (tag 'CoContra_Child3')",
    "Lines 141, 142: Expected error (tag 'CoContra_Child5')",
    "Lines 195, 196: Expected error (tag 'ContraToContraToContra_WithTA')"
  ],
  "generics_variance_inference.py": [
    "Line 26: Unexpected errors ['EXPECTED ClassA[float, int, int] <: ClassA[float, int, float]']",
    "Line 29: Unexpected errors ['EXPECTED ClassA[int, float, float] <: ClassA[int, int, float]']",
    "Line 40: Unexpected errors ['EXPECTED ShouldBeCovariant1[int] <: ShouldBeCovariant1[float]']",
    "Line 48: Unexpected errors ['EXPECTED ShouldBeCovariant2[int] <: ShouldBeCovariant2[float]']",
    "Line 57: Unexpected errors ['EXPECTED ShouldBeCovariant3[int] <: ShouldBeCovariant3[float]']",
    "Line 66: Unexpected errors ['EXPECTED ShouldBeCovariant4[int] <: ShouldBeCovariant4[float]', 'Expected 0 positional arguments, got 1']",
    "Line 79: Unexpected errors ['EXPECTED ShouldBeCovariant5[int] <: ShouldBeCovariant5[float]']",
    "Line 91: Unexpected errors ['Could not find name `value`']",
    "Line 150: Unexpected errors ['EXPECTED ShouldBeContravariant1[float] <: ShouldBeContravariant1[int]']",
    "Line 182: Unexpected errors ['EXPECTED ShouldBeCovariant6[int] <: ShouldBeCovariant6[float]']",
    "Line 193: Unexpected errors ['EXPECTED ShouldBeContravariant2[float] <: ShouldBeContravariant2[int]']"
  ],
  "historical_positional.py": [
    "Line 18: Expected 1 errors",
    "Line 26: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 43: Expected 1 errors"
  ],
  "literals_interactions.py": [
    "Line 49: Unexpected errors ['assert_type(Any, IO[str]) failed']",
    "Line 50: Unexpected errors ['assert_type(Any, IO[bytes]) failed']",
    "Line 51: Unexpected errors ['assert_type(Any, IO[Any]) failed']",
    "Line 71: Unexpected errors ['EXPECTED Matrix[Literal[3], Literal[7]] <: Matrix[Literal[3], TypeVar[C]]']",
    "Line 72: Unexpected errors ['assert_type(Matrix[Literal[2], TypeVar[C]], Matrix[Literal[2], Literal[7]]) failed']",
    "Line 106: Unexpected errors [\"EXPECTED str <: Literal['ABORTED', 'MALFORMED']\"]"
  ],
  "literals_literalstring.py": [
    "Line 120: Expected 1 errors",
    "Line 48: Unexpected errors ['assert_type(str, LiteralString) failed']",
    "Line 52: Unexpected errors ['assert_type(str, LiteralString) failed']",
    "Line 53: Unexpected errors ['EXPECTED LiteralString <: Buffer']",
    "Line 57: Unexpected errors ['`LiteralString` has no attribute `__iadd__`']",
    "Line 58: Unexpected errors ['`LiteralString` has no attribute `__iadd__`']",
    "Line 63: Unexpected errors ['assert_type(str, LiteralString) failed']",
    "Line 68: Unexpected errors ['assert_type(Any, str) failed', 'EXPECTED Literal[1] <: Buffer']",
    "Line 111: Unexpected errors [\"assert_type(str, Literal['hello']) failed\"]",
    "Line 116: Unexpected errors ['assert_type(str, LiteralString) failed']",
    "Line 130: Unexpected errors ['EXPECTED Container[str] <: Container[LiteralString]']",
    "Line 165: Unexpected errors ['assert_type(Any, C) failed']",
    "Line 166: Unexpected errors ['assert_type(Any, B) failed']",
    "Line 167: Unexpected errors ['assert_type(Any, A) failed', 'EXPECTED Literal[1] <: Buffer']"
  ],
  "literals_parameterizations.py": [
    "Line 46: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 26: Unexpected errors ['Invalid literal expression']",
    "Line 33: Unexpected errors ['Invalid literal expression', 'Invalid literal expression', 'Invalid literal expression', 'Invalid literal expression']",
    "Line 35: Unexpected errors ['Invalid literal expression', 'Invalid literal expression']"
  ],
  "literals_semantics.py": [
    "Line 38: Unexpected errors ['Invalid literal expression', 'Could not find name `foo`', 'Invalid literal expression']",
    "Line 39: Unexpected errors ['Invalid literal expression']"
  ],
  "namedtuples_define_class.py": [
    "Line 59: Expected 1 errors",
    "Line 79: Expected 1 errors",
    "Line 21: Unexpected errors ['EXPECTED Literal[1] <: str', 'EXPECTED Literal[2] <: None']",
    "Line 23: Unexpected errors ['assert_type(Any, int) failed', '`Point` has no attribute `__getitem__`']",
    "Line 24: Unexpected errors ['assert_type(Any, int) failed', '`Point` has no attribute `__getitem__`']",
    "Line 25: Unexpected errors ['assert_type(Any, str) failed', '`Point` has no attribute `__getitem__`']",
    "Line 26: Unexpected errors ['assert_type(Any, str) failed', '`Point` has no attribute `__getitem__`']",
    "Line 27: Unexpected errors ['assert_type(Any, int) failed', '`Point` has no attribute `__getitem__`']",
    "Line 28: Unexpected errors ['assert_type(Any, int) failed', '`Point` has no attribute `__getitem__`']",
    "Line 29: Unexpected errors ['assert_type(Any, tuple[int, int]) failed', '`Point` has no attribute `__getitem__`']",
    "Line 30: Unexpected errors ['assert_type(Any, tuple[int, int, str]) failed', '`Point` has no attribute `__getitem__`']",
    "Line 35: Unexpected errors ['EXPECTED Literal[1] <: str', 'EXPECTED Literal[2] <: None', 'Expected 2 positional arguments, got 3']",
    "Line 38: Unexpected errors ['Expected 1 more positional argument']",
    "Line 41: Unexpected errors ['Expected 1 more positional argument']",
    "Line 72: Unexpected errors ['EXPECTED Literal[1] <: str', 'EXPECTED Literal[2] <: None', 'Expected 2 positional arguments, got 3']",
    "Line 73: Unexpected errors ['EXPECTED PointWithName <: tuple[int, int, str]']",
    "Line 93: Unexpected errors ['EXPECTED float <: None']",
    "Line 94: Unexpected errors ['assert_type(Property[Any], Property[float]) failed']",
    "Line 95: Unexpected errors ['assert_type(Any, float) failed', '`Property[Unknown]` has no attribute `__getitem__`']",
    "Line 96: Unexpected errors ['assert_type(Any, float) failed']"
  ],
  "namedtuples_define_functional.py": [
    "Line 14: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point1, type[tuple[Any, ...]]]']",
    "Line 15: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point1, type[tuple[Any, ...]]]']",
    "Line 19: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point2, type[tuple[Any, ...]]]']",
    "Line 20: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point2, type[tuple[Any, ...]]]']",
    "Line 24: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point3, type[tuple[Any, ...]]]']",
    "Line 25: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point3, type[tuple[Any, ...]]]']",
    "Line 29: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point4, type[tuple[Any, ...]]]']",
    "Line 30: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point4, type[tuple[Any, ...]]]']",
    "Line 33: Unexpected errors ['EXPECTED list[tuple[str, type[int]]] <: None']",
    "Line 34: Unexpected errors ['Expected a callable, got NamedTuple']",
    "Line 35: Unexpected errors ['Expected a callable, got NamedTuple']",
    "Line 39: Unexpected errors [\"EXPECTED tuple[tuple[Literal['x'], type[int]], tuple[Literal['y'], type[int]]] <: None\"]",
    "Line 40: Unexpected errors ['Expected a callable, got NamedTuple']",
    "Line 41: Unexpected errors ['Expected a callable, got NamedTuple']",
    "Line 57: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[NT4, type[tuple[Any, ...]]]']",
    "Line 64: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[NT5, type[tuple[Any, ...]]]']",
    "Line 65: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[NT5, type[tuple[Any, ...]]]']"
  ],
  "namedtuples_type_compat.py": [
    "Line 19: Unexpected errors ['Expected 1 more positional argument']",
    "Line 20: Unexpected errors ['EXPECTED Point <: tuple[int, int, str]']",
    "Line 21: Unexpected errors ['EXPECTED Point <: tuple[Any, ...]']",
    "Line 27: Unexpected errors ['EXPECTED Point <: tuple[float, float, str]']"
  ],
  "namedtuples_usage.py": [
    "Line 40: Expected 1 errors",
    "Line 19: Unexpected errors ['EXPECTED Literal[1] <: str', 'EXPECTED Literal[2] <: None']",
    "Line 27: Unexpected errors ['assert_type(Any, int) failed', '`Point` has no attribute `__getitem__`']",
    "Line 28: Unexpected errors ['assert_type(Any, int) failed', '`Point` has no attribute `__getitem__`']",
    "Line 29: Unexpected errors ['assert_type(Any, str) failed', '`Point` has no attribute `__getitem__`']",
    "Line 30: Unexpected errors ['assert_type(Any, str) failed', '`Point` has no attribute `__getitem__`']",
    "Line 31: Unexpected errors ['assert_type(Any, int) failed', '`Point` has no attribute `__getitem__`']",
    "Line 32: Unexpected errors ['assert_type(Any, int) failed', '`Point` has no attribute `__getitem__`']",
    "Line 48: Unexpected errors ['Type `Point` is not iterable']",
    "Line 49: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 50: Unexpected errors ['assert_type(Any, str) failed']",
    "Line 60: Unexpected errors ['EXPECTED Literal[1] <: str', 'EXPECTED Literal[1] <: None']",
    "Line 61: Unexpected errors ['Type `PointWithName` is not iterable']"
  ],
  "narrowing_typeguard.py": [
    "Line 102: Expected 1 errors",
    "Line 107: Expected 1 errors",
    "Line 17: Unexpected errors ['assert_type(tuple[?_, ?_], tuple[str, str]) failed']",
    "Line 31: Unexpected errors ['EXPECTED type[int] <: type[@_]']",
    "Line 32: Unexpected errors ['assert_type(set[?_], set[int]) failed']",
    "Line 47: Unexpected errors ['EXPECTED (val: object) -> TypeGuard[int] <: (ParamSpec(@_)) -> TypeGuard[int]']",
    "Line 52: Unexpected errors ['EXPECTED type[type] <: type[TypeVar[Self]]', 'Expected 2 more positional arguments', 'EXPECTED TypeVar[Self] <: UnionType | type | tuple[Unknown, ...]', 'EXPECTED A <: str']",
    "Line 55: Unexpected errors ['EXPECTED type[type] <: type[TypeVar[Self]]', 'Expected 2 more positional arguments', 'EXPECTED TypeVar[Self] <: UnionType | type | tuple[Unknown, ...]', 'EXPECTED ?_ <: str']",
    "Line 72: Unexpected errors ['Expected a callable, got classmethod[(cls: A, val: object) -> TypeGuard[int]]']",
    "Line 73: Unexpected errors ['assert_type(object, int) failed']",
    "Line 76: Unexpected errors ['Expected a callable, got classmethod[(cls: A, val: object) -> TypeGuard[int]]']",
    "Line 77: Unexpected errors ['assert_type(object, int) failed']",
    "Line 80: Unexpected errors ['EXPECTED object <: Args[?_]']",
    "Line 81: Unexpected errors ['assert_type(object, int) failed']",
    "Line 84: Unexpected errors ['EXPECTED object <: Args[?_]']",
    "Line 85: Unexpected errors ['assert_type(object, int) failed']",
    "Line 89: Unexpected errors ['assert_type(A, B) failed']",
    "Line 93: Unexpected errors ['assert_type(A, B) failed']",
    "Line 147: Unexpected errors ['EXPECTED (val: object) -> TypeGuard[int] <: CallableBoolProto']"
  ],
  "narrowing_typeis.py": [
    "Line 105: Expected 1 errors",
    "Line 110: Expected 1 errors",
    "Line 195: Expected 1 errors",
    "Line 199: Expected 1 errors",
    "Line 15: Unexpected errors ['EXPECTED bool <: TypeIs[tuple[?_, ?_]]']",
    "Line 19: Unexpected errors ['assert_type(tuple[str, ...], tuple[str, str]) failed']",
    "Line 28: Unexpected errors ['EXPECTED bool <: TypeIs[Awaitable[Any]]']",
    "Line 35: Unexpected errors ['Expression is not awaitable']",
    "Line 38: Unexpected errors ['assert_type(Awaitable[int] | int, int) failed']",
    "Line 45: Unexpected errors ['EXPECTED bool <: TypeIs[int]']",
    "Line 49: Unexpected errors ['EXPECTED bool <: TypeIs[int]']",
    "Line 51: Unexpected errors ['EXPECTED (val: object) -> TypeIs[int] <: (ParamSpec(@_)) -> TypeIs[int]']",
    "Line 53: Unexpected errors ['EXPECTED bool <: TypeIs[int]']",
    "Line 56: Unexpected errors ['EXPECTED bool <: TypeIs[A]', 'EXPECTED type[type] <: type[TypeVar[Self]]', 'Expected 2 more positional arguments', 'EXPECTED TypeVar[Self] <: UnionType | type | tuple[Unknown, ...]', 'EXPECTED A <: str']",
    "Line 59: Unexpected errors ['EXPECTED bool <: TypeIs[?_]', 'EXPECTED type[type] <: type[TypeVar[Self]]', 'Expected 2 more positional arguments', 'EXPECTED TypeVar[Self] <: UnionType | type | tuple[Unknown, ...]', 'EXPECTED ?_ <: str']",
    "Line 72: Unexpected errors ['assert_type(object, int) failed']",
    "Line 75: Unexpected errors ['Expected a callable, got classmethod[(cls: A, val: object) -> TypeIs[int]]']",
    "Line 76: Unexpected errors ['assert_type(object, int) failed']",
    "Line 79: Unexpected errors ['Expected a callable, got classmethod[(cls: A, val: object) -> TypeIs[int]]']",
    "Line 80: Unexpected errors ['assert_type(object, int) failed']",
    "Line 83: Unexpected errors ['EXPECTED object <: Args[?_]']",
    "Line 84: Unexpected errors ['assert_type(object, int) failed']",
    "Line 87: Unexpected errors ['EXPECTED object <: Args[?_]']",
    "Line 88: Unexpected errors ['assert_type(object, int) failed']",
    "Line 92: Unexpected errors ['assert_type(object, B) failed']",
    "Line 96: Unexpected errors ['assert_type(object, B) failed']",
    "Line 106: Unexpected errors ['EXPECTED Literal[False] <: TypeIs[int]']",
    "Line 111: Unexpected errors ['EXPECTED Literal[False] <: TypeIs[int]']",
    "Line 128: Unexpected errors ['EXPECTED bool <: TypeIs[int]']",
    "Line 151: Unexpected errors ['EXPECTED (val: object) -> TypeIs[int] <: CallableBoolProto']",
    "Line 163: Unexpected errors ['EXPECTED bool <: TypeIs[int]']",
    "Line 183: Unexpected errors ['EXPECTED bool <: TypeIs[int]']",
    "Line 187: Unexpected errors ['EXPECTED bool <: TypeIs[bool]']",
    "Line 196: Unexpected errors ['EXPECTED bool <: TypeIs[str]']",
    "Line 200: Unexpected errors ['EXPECTED bool <: TypeIs[list[int]]']"
  ],
  "overloads_basic.py": [
    "Lines 62, 63: Expected error (tag 'func1')",
    "Lines 74, 75: Expected error (tag 'func2')",
    "Line 35: Unexpected errors ['assert_type(bytes | int, int) failed']",
    "Line 36: Unexpected errors ['assert_type(bytes | int, bytes) failed']"
  ],
  "protocols_class_objects.py": [
    "Line 29: Expected 1 errors",
    "Line 34: Expected 1 errors",
    "Line 30: Unexpected errors ['EXPECTED type[Concrete] <: type[Proto]']",
    "Line 35: Unexpected errors ['EXPECTED type[Concrete] <: type[Proto]']",
    "Line 59: Unexpected errors ['EXPECTED type[ConcreteA] <: ProtoA2']",
    "Line 105: Unexpected errors ['EXPECTED type[ConcreteC1] <: ProtoC2']",
    "Line 109: Unexpected errors ['EXPECTED type[ConcreteC3] <: ProtoC2']"
  ],
  "protocols_definition.py": [
    "Line 115: Expected 1 errors",
    "Line 116: Expected 1 errors",
    "Line 117: Expected 1 errors",
    "Line 157: Expected 1 errors",
    "Line 158: Expected 1 errors",
    "Line 159: Expected 1 errors",
    "Line 160: Expected 1 errors",
    "Line 218: Expected 1 errors",
    "Line 285: Expected 1 errors",
    "Line 286: Expected 1 errors",
    "Line 287: Expected 1 errors",
    "Line 288: Expected 1 errors",
    "Line 289: Expected 1 errors",
    "Line 339: Expected 1 errors",
    "Line 341: Expected 1 errors",
    "Line 27: Unexpected errors [\"Missing argument 'mode'\"]",
    "Line 39: Unexpected errors ['EXPECTED None <: int']",
    "Line 43: Unexpected errors ['EXPECTED () -> int <: (ParamSpec(@_)) -> int']",
    "Line 102: Unexpected errors ['EXPECTED Literal[2] <: float']",
    "Line 148: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 172: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 182: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 190: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 194: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 199: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 216: Unexpected errors ['Expected 1 more positional argument']",
    "Line 245: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 249: Unexpected errors ['EXPECTED (a: int, b: int) -> float <: (ParamSpec(@_)) -> float']",
    "Line 251: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 266: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 271: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 275: Unexpected errors ['EXPECTED (self: Concrete5_Bad5, a: int, b: int) -> float <: (ParamSpec(@_)) -> float']",
    "Line 277: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 297: Unexpected errors ['Could not find name `val1`']",
    "Line 305: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 307: Unexpected errors ['Could not find name `val1`']",
    "Line 313: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 318: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 324: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 328: Unexpected errors ['EXPECTED Literal[0] <: float']",
    "Line 333: Unexpected errors ['EXPECTED Literal[0] <: float']"
  ],
  "protocols_explicit.py": [
    "Line 56: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 90: Expected 1 errors",
    "Line 110: Expected 1 errors",
    "Line 135: Expected 1 errors",
    "Line 165: Expected 1 errors"
  ],
  "protocols_generic.py": [
    "Line 40: Expected 1 errors",
    "Line 146: Expected 1 errors",
    "Line 147: Expected 1 errors",
    "Line 55: Unexpected errors ['EXPECTED Box[int] <: Box[float]']",
    "Line 65: Unexpected errors ['EXPECTED Sender[float] <: Sender[int]']",
    "Line 87: Unexpected errors ['TODO: Expr::attr_infer attribute base undefined for type: ?_ (trying to access get_parent)']",
    "Line 100: Unexpected errors ['EXPECTED Forall[T, (self: T) -> T] <: (Any) -> Any | None']",
    "Line 109: Unexpected errors ['EXPECTED Forall[T, (self: T) -> T] <: (Any) -> Any | None']"
  ],
  "protocols_merging.py": [
    "Line 82: Expected 1 errors"
  ],
  "protocols_modules.py": [
    "Line 10: Unexpected errors ['Could not find import of `_protocols_modules1`, Could not find path for `_protocols_modules1`']",
    "Line 11: Unexpected errors ['Could not find import of `_protocols_modules2`, Could not find path for `_protocols_modules2`']",
    "Line 25: Unexpected errors ['EXPECTED Module[_protocols_modules1] <: Options1']",
    "Line 47: Unexpected errors ['EXPECTED Module[_protocols_modules2] <: Reporter1']"
  ],
  "protocols_recursive.py": [
    "Line 81: Unexpected errors ['assert_type(Any, list[int]) failed']"
  ],
  "protocols_runtime_checkable.py": [
    "Line 23: Expected 1 errors",
    "Line 55: Expected 1 errors",
    "Line 61: Expected 1 errors",
    "Line 88: Expected 1 errors",
    "Line 92: Expected 1 errors",
    "Line 96: Expected 1 errors"
  ],
  "protocols_self.py": [],
  "protocols_subtyping.py": [
    "Line 16: Expected 1 errors",
    "Line 79: Expected 1 errors",
    "Line 80: Expected 1 errors",
    "Line 102: Expected 1 errors",
    "Line 103: Expected 1 errors"
  ],
  "protocols_variance.py": [
    "Line 21: Expected 1 errors",
    "Line 40: Expected 1 errors",
    "Line 56: Expected 1 errors",
    "Line 61: Expected 1 errors",
    "Line 66: Expected 1 errors",
    "Line 71: Expected 1 errors",
    "Line 104: Expected 1 errors"
  ],
  "qualifiers_annotated.py": [
    "Line 47: Expected 1 errors",
    "Line 49: Expected 1 errors",
    "Line 53: Expected 1 errors",
    "Line 64: Expected 1 errors",
    "Line 76: Expected 1 errors",
    "Line 77: Expected 1 errors",
    "Line 85: Expected 1 errors",
    "Line 36: Unexpected errors ['Invalid literal expression']",
    "Line 81: Unexpected errors ['Expected a callable, got type[?_]']",
    "Line 98: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `ClassVar[int]`']",
    "Line 100: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `Final[int]`']",
    "Line 110: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `Required[int]`']",
    "Line 112: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `NotRequired[int]`']"
  ],
  "qualifiers_final_annotation.py": [
    "Line 16: Expected 1 errors",
    "Line 34: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 65: Expected 1 errors",
    "Line 71: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 94: Expected 1 errors",
    "Line 107: Expected 1 errors",
    "Line 108: Expected 1 errors",
    "Line 121: Expected 1 errors",
    "Line 141: Expected 1 errors",
    "Line 147: Expected 1 errors",
    "Line 149: Expected 1 errors",
    "Line 155: Expected 1 errors",
    "Line 131: Unexpected errors ['EXPECTED list[tuple[str, type[int]]] <: None']",
    "Line 133: Unexpected errors ['Expected a callable, got NamedTuple']",
    "Line 139: Unexpected errors ['TODO: StmtGlobal - Bindings::stmt']"
  ],
  "qualifiers_final_decorator.py": [
    "Line 21: Expected 1 errors",
    "Line 56: Expected 1 errors",
    "Line 118: Expected 1 errors",
    "Lines 59, 60: Expected error (tag 'method2')",
    "Lines 67, 75: Expected error (tag 'method4')",
    "Lines 80, 89: Expected error (tag 'Derived3')",
    "Lines 84, 85, 86: Expected error (tag 'Derived3-2')",
    "Lines 94, 102: Expected error (tag 'Derived4')",
    "Lines 125, 126: Expected error (tag 'func')",
    "Line 8: Unexpected errors ['Could not find import of `_qualifiers_final_decorator`, Could not find path for `_qualifiers_final_decorator`']",
    "Line 36: Unexpected errors ['EXPECTED () -> None <: (ParamSpec(@_)) -> None']"
  ],
  "specialtypes_any.py": [
    "Line 62: Unexpected errors ['assert_type(tuple[Any], tuple[Any, ...]) failed']",
    "Line 64: Unexpected errors ['EXPECTED tuple[Error] <: tuple[str, ...]']",
    "Line 65: Unexpected errors ['EXPECTED tuple[Error] <: tuple[int, ...]']",
    "Line 72: Unexpected errors ['assert_type(Callable, (...) -> Any) failed']",
    "Line 74: Unexpected errors ['EXPECTED Callable <: () -> Any']",
    "Line 75: Unexpected errors ['EXPECTED Callable <: (int, str) -> None']",
    "Line 87: Unexpected errors ['Object of class `ClassA` has no attribute `method2`']",
    "Line 88: Unexpected errors ['Class `ClassA` has no class attribute `method3`']"
  ],
  "specialtypes_never.py": [
    "Line 19: Expected 1 errors",
    "Line 16: Unexpected errors ['EXPECTED None <: NoReturn']",
    "Line 21: Unexpected errors ['EXPECTED None <: NoReturn']",
    "Line 32: Unexpected errors [\"EXPECTED Literal['whatever works'] <: int\"]",
    "Line 77: Unexpected errors ['EXPECTED None <: Never']"
  ],
  "specialtypes_none.py": [
    "Line 40: Unexpected errors ['EXPECTED type[type] <: type[TypeVar[Self]]', 'Expected 2 more positional arguments', 'EXPECTED TypeVar[Self] <: type[None]', 'EXPECTED None <: str']"
  ],
  "specialtypes_promotions.py": [
    "Line 7: Unexpected errors ['EXPECTED Literal[1] <: float']",
    "Line 8: Unexpected errors ['EXPECTED float <: complex']",
    "Line 9: Unexpected errors ['EXPECTED Literal[1] <: complex']"
  ],
  "specialtypes_type.py": [
    "Line 70: Expected 1 errors",
    "Line 39: Unexpected errors ['Expected a callable, got type[?_]']",
    "Line 44: Unexpected errors ['assert_type(Any, TeamUser) failed', 'EXPECTED type[TeamUser] <: type[@_]']",
    "Line 51: Unexpected errors ['Expected a callable, got type[BasicUser | ProUser]']",
    "Line 54: Unexpected errors ['EXPECTED type[BasicUser] <: type[BasicUser | ProUser]']",
    "Line 55: Unexpected errors ['EXPECTED type[ProUser] <: type[BasicUser | ProUser]']",
    "Line 68: Unexpected errors ['EXPECTED type[User] <: type[@_]']",
    "Line 69: Unexpected errors ['EXPECTED type[tuple] <: type[@_]']",
    "Line 84: Unexpected errors ['assert_type(type, type[Any]) failed']",
    "Line 98: Unexpected errors ['assert_type(property, tuple[type, ...]) failed']",
    "Line 99: Unexpected errors ['Object of class `type` has no attribute `unknown`']",
    "Line 100: Unexpected errors ['Object of class `type` has no attribute `unknown`']",
    "Line 102: Unexpected errors ['assert_type(property, tuple[type, ...]) failed']",
    "Line 106: Unexpected errors ['assert_type(Any, tuple[type, ...]) failed', 'TODO: Expr::attr_infer attribute base undefined for type: Type (trying to access __mro__)']",
    "Line 107: Unexpected errors ['TODO: Expr::attr_infer attribute base undefined for type: Type (trying to access unknown)']",
    "Line 108: Unexpected errors ['TODO: Expr::attr_infer attribute base undefined for type: Type (trying to access unknown)']",
    "Line 110: Unexpected errors ['assert_type(property, tuple[type, ...]) failed']",
    "Line 137: Unexpected errors ['assert_type(Type, type[Any]) failed']",
    "Line 139: Unexpected errors ['assert_type(type, type[Any]) failed']",
    "Line 152: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[TA7, type[type[TypeVar[T]]]]\"]",
    "Line 156: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[TA8, type[type[TypeVar[T]]]]\"]",
    "Line 160: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 161: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 165: Unexpected errors ['EXPECTED type <: (...) -> Any']",
    "Line 166: Unexpected errors ['EXPECTED type <: (int, int) -> int']",
    "Line 169: Unexpected errors ['EXPECTED type <: type[int]']",
    "Line 170: Unexpected errors ['EXPECTED type <: type[Any]']",
    "Line 175: Unexpected errors ['EXPECTED type <: type[?_]']"
  ],
  "tuples_type_compat.py": [
    "Line 14: Unexpected errors ['EXPECTED tuple[int, int] <: tuple[float, complex]']",
    "Line 22: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 27: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 28: Unexpected errors ['EXPECTED tuple[int] <: tuple[int, Error]']",
    "Line 47: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 59: Unexpected errors ['EXPECTED tuple[Any] <: tuple[int, int]']",
    "Line 71: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 74: Unexpected errors ['assert_type(tuple[int] | tuple[int, Any, int] | tuple[str, str], tuple[int]) failed']",
    "Line 78: Unexpected errors ['assert_type(tuple[int] | tuple[int, Any, int] | tuple[str, str], tuple[int, int] | tuple[str, str]) failed']",
    "Line 82: Unexpected errors ['assert_type(tuple[int] | tuple[int, Any, int] | tuple[str, str], tuple[int, str, int]) failed']",
    "Line 91: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 93: Unexpected errors ['Cannot unpack tuple[int] | tuple[int, Error, int] | tuple[str, str] (of size 2) into 1 value', 'Cannot unpack tuple[int] | tuple[int, Error, int] | tuple[str, str] (of size 3) into 1 value']",
    "Line 95: Unexpected errors ['assert_type(tuple[int] | tuple[int, Any, int] | tuple[str, str], tuple[int]) failed']",
    "Line 97: Unexpected errors ['Cannot unpack tuple[int] | tuple[int, Error, int] | tuple[str, str] (of size 1) into 2 values', 'Cannot unpack tuple[int] | tuple[int, Error, int] | tuple[str, str] (of size 3) into 2 values']",
    "Line 99: Unexpected errors ['assert_type(tuple[int] | tuple[int, Any, int] | tuple[str, str], tuple[int, int] | tuple[str, str]) failed']",
    "Line 101: Unexpected errors ['Cannot unpack tuple[int] | tuple[int, Error, int] | tuple[str, str] (of size 1) into 3 values', 'Cannot unpack tuple[int] | tuple[int, Error, int] | tuple[str, str] (of size 2) into 3 values']",
    "Line 103: Unexpected errors ['assert_type(tuple[int] | tuple[int, Any, int] | tuple[str, str], tuple[int, str, int]) failed']",
    "Line 115: Unexpected errors ['assert_type(tuple[int | str, int | str], tuple[int | str, str]) failed']",
    "Line 117: Unexpected errors ['assert_type(tuple[int | str, int | str], tuple[int | str, int]) failed']",
    "Line 134: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 139: Unexpected errors ['assert_type(Sequence[int | Any], Sequence[int | str]) failed']",
    "Line 143: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 146: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'EXPECTED tuple[Literal[1]] <: tuple[int, Error]']",
    "Line 148: Unexpected errors [\"EXPECTED tuple[Literal[1], Literal[''], Literal['']] <: tuple[int, Error]\"]",
    "Line 153: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'EXPECTED tuple[Literal[1], Literal[2]] <: tuple[int, Error, int]']",
    "Line 155: Unexpected errors [\"EXPECTED tuple[Literal[1], Literal[''], Literal[''], Literal[2]] <: tuple[int, Error, int]\"]",
    "Line 159: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'EXPECTED tuple[Literal[1]] <: tuple[Error, int]']",
    "Line 161: Unexpected errors [\"EXPECTED tuple[Literal[''], Literal[''], Literal[1]] <: tuple[Error, int]\"]",
    "Line 167: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'EXPECTED tuple[str, str] <: tuple[str, str, Error]']",
    "Line 169: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 170: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'EXPECTED tuple[str, str] <: tuple[str, str, Error]']",
    "Line 172: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'EXPECTED tuple[str, str] <: tuple[str, Error, str]']",
    "Line 173: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 174: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']"
  ],
  "tuples_type_form.py": [],
  "tuples_unpacked.py": [
    "Line 59: Expected 1 errors",
    "Lines 60, 61: Expected error (tag 't14')",
    "Line 16: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 17: Unexpected errors ['assert_type(tuple[int, Any, str], tuple[int, bool, bool, str]) failed']",
    "Line 18: Unexpected errors ['assert_type(tuple[int, Any, str], tuple[Any, bool, str]) failed', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 19: Unexpected errors ['assert_type(tuple[int, Any, str], tuple[int, bool, Any]) failed', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 25: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 26: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 31: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer', \"Missing argument 'base'\", 'EXPECTED Literal[1] <: bytearray | bytes | str', \"Missing argument 'base'\", 'EXPECTED Literal[1] <: bytearray | bytes | str']",
    "Line 33: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 38: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 39: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 49: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer']",
    "Line 50: Unexpected errors ['TODO: Starred(ExprStarred - Answers::expr_infer', 'TODO: Starred(ExprStarred - Answers::expr_infer']"
  ],
  "typeddicts_alt_syntax.py": [
    "Line 45: Expected 1 errors",
    "Line 10: Unexpected errors ['Expected a callable, got type[TypedDict]']",
    "Line 14: Unexpected errors ['Expected a callable, got type[TypedDict]']"
  ],
  "typeddicts_class_syntax.py": [
    "Line 33: Expected 1 errors",
    "Line 49: Expected 1 errors",
    "Line 34: Unexpected errors ['TypedDict item `method2` may not be initialized.']",
    "Line 39: Unexpected errors ['TypedDict item `method3` may not be initialized.']"
  ],
  "typeddicts_final.py": [
    "Line 26: Unexpected errors [\"Invalid key for TypedDict `Movie`, got `Literal['name', 'year']`\"]"
  ],
  "typeddicts_inheritance.py": [
    "Line 65: Expected 1 errors",
    "Lines 54, 55: Expected error (tag 'Y1')"
  ],
  "typeddicts_operations.py": [
    "Line 41: Unexpected errors [\"Missing argument 'default'\"]",
    "Line 60: Unexpected errors ['assert_type(object | Any, str | None) failed', \"Missing argument 'default'\"]",
    "Line 64: Unexpected errors ['TODO: StmtDelete - Bindings::stmt']"
  ],
  "typeddicts_readonly.py": [
    "Line 36: Expected 1 errors",
    "Line 61: Expected 1 errors",
    "Line 31: Unexpected errors ['Expected a callable, got type[TypedDict]', 'TODO: Answers::apply_special_form cannot handle `ReadOnly[list[str]]`']",
    "Line 37: Unexpected errors ['Object of class `str` has no attribute `append`']",
    "Line 56: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `NotRequired[ReadOnly[int]]`']"
  ],
  "typeddicts_readonly_consistency.py": [
    "Line 38: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 79: Unexpected errors ['EXPECTED TypedDict[C2] <: TypedDict[A2]']"
  ],
  "typeddicts_readonly_inheritance.py": [
    "Line 50: Expected 1 errors",
    "Line 94: Expected 1 errors",
    "Line 98: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 119: Expected 1 errors",
    "Line 132: Expected 1 errors"
  ],
  "typeddicts_readonly_kwargs.py": [
    "Line 36: Unexpected errors ['EXPECTED (**Unpack[TypedDict[ReadOnlyArgs]]) -> None <: Function']"
  ],
  "typeddicts_readonly_update.py": [
    "Line 34: Unexpected errors ['Object of class `Mapping` has no attribute `update`']"
  ],
  "typeddicts_required.py": [
    "Line 12: Expected 1 errors",
    "Line 19: Expected 1 errors",
    "Line 62: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 68: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `Required[int]`']",
    "Line 70: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `Required[Annotated[int, \"\"]]`']",
    "Line 73: Unexpected errors ['Expected a callable, got type[TypedDict]']",
    "Line 74: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `Required[str]`', 'TODO: Answers::apply_special_form cannot handle `NotRequired[\"RecursiveMovie\"]`']"
  ],
  "typeddicts_type_consistency.py": [
    "Line 21: Expected 1 errors",
    "Line 88: Unexpected errors ['Expected a callable, got type[TypedDict]']",
    "Line 91: Unexpected errors ['EXPECTED int | str | str <: str']",
    "Line 92: Unexpected errors ['EXPECTED int | str | int <: int']",
    "Line 94: Unexpected errors ['Expected a callable, got type[TypedDict]']",
    "Line 97: Unexpected errors ['Expected 1 more positional argument', 'EXPECTED int | str | @_ <: str | None']",
    "Line 103: Unexpected errors ['EXPECTED int | str | int <: int']",
    "Line 151: Unexpected errors [\"EXPECTED dict[str, int] <: Literal[''] | TypedDict[Inner3]\"]"
  ],
  "typeddicts_usage.py": [
    "Line 35: Expected 1 errors",
    "Line 40: Expected 1 errors"
  ]
}