@generated
{
  "aliases_explicit.py": [
    "Line 69: Expected 1 errors",
    "Line 70: Expected 1 errors",
    "Line 71: Expected 1 errors",
    "Line 84: Expected 1 errors",
    "Line 85: Expected 1 errors",
    "Line 86: Expected 1 errors",
    "Line 90: Expected 1 errors",
    "Line 38: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[GoodTypeAlias6, type[tuple[int, int, TypeVar[S], TypeVar[T]]]]\"]",
    "Line 41: Unexpected errors ['untype, got list[type[str]]']",
    "Line 53: Unexpected errors ['assert_type(list[str] | tuple[TypeVar[T], ...], list[str] | tuple[str, ...]) failed']",
    "Line 54: Unexpected errors ['assert_type(Any, tuple[int, int, int, str]) failed']",
    "Line 57: Unexpected errors ['assert_type((int, ParamSpec(ParamSpec[P])) -> Any, (int, str, str) -> None) failed']",
    "Line 60: Unexpected errors ['assert_type((ParamSpec(ParamSpec[P])) -> None, (...) -> None) failed']",
    "Line 98: Unexpected errors ['assert_type(list[Any], list[str]) failed']"
  ],
  "aliases_implicit.py": [
    "Line 78: Expected 1 errors",
    "Line 79: Expected 1 errors",
    "Line 80: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 112: Expected 1 errors",
    "Line 113: Expected 1 errors",
    "Line 117: Expected 1 errors",
    "Line 14: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[Vector, type[Iterable[tuple[TypeVar[TFloat], TypeVar[TFloat]]]]]\"]",
    "Line 18: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[Vector, type[Iterable[tuple[TypeVar[TFloat], TypeVar[TFloat]]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[Vector, type[Iterable[tuple[TypeVar[TFloat], TypeVar[TFloat]]]]]\"]",
    "Line 51: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GoodTypeAlias6, type[tuple[int, int, TypeVar[S], TypeVar[T]]]]\"]",
    "Line 54: Unexpected errors ['untype, got list[type[str]]']",
    "Line 64: Unexpected errors ['assert_type(list[str] | tuple[TypeVar[T], ...], list[str] | tuple[str, ...]) failed']",
    "Line 65: Unexpected errors ['assert_type(Any, tuple[int, int, int, str]) failed']",
    "Line 68: Unexpected errors ['assert_type((int, ParamSpec(ParamSpec[P])) -> Any, (int, str, str) -> None) failed']",
    "Line 72: Unexpected errors ['assert_type((ParamSpec(ParamSpec[P])) -> None, (...) -> None) failed']"
  ],
  "aliases_newtype.py": [
    "Line 11: Expected 1 errors",
    "Line 32: Expected 1 errors",
    "Line 44: Expected 1 errors",
    "Line 47: Expected 1 errors",
    "Line 49: Expected 1 errors",
    "Line 51: Expected 1 errors",
    "Line 58: Expected 1 errors",
    "Line 62: Expected 1 errors",
    "Line 13: Unexpected errors ['untype, got NewType']"
  ],
  "aliases_recursive.py": [
    "Line 19: Expected 1 errors",
    "Line 20: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 39: Expected 1 errors",
    "Line 50: Expected 1 errors",
    "Line 51: Expected 1 errors",
    "Line 52: Expected 1 errors",
    "Line 72: Expected 1 errors",
    "Line 75: Expected 1 errors",
    "Line 14: Unexpected errors [\"untype, got Literal['Json']\", \"untype, got Literal['Json']\"]",
    "Line 24: Unexpected errors [\"untype, got Literal['Json2']\", \"untype, got Literal['Json2']\"]",
    "Line 30: Unexpected errors [\"untype, got Literal['RecursiveTuple']\"]",
    "Line 42: Unexpected errors [\"untype, got Literal['RecursiveMapping']\"]",
    "Line 58: Unexpected errors ['Object of class `str` has no attribute `__or__`']",
    "Line 59: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GenericTypeAlias1, type[list[Error]]]\"]",
    "Line 62: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GenericTypeAlias1, type[list[Error]]]\"]",
    "Line 65: Unexpected errors ['Object of class `str` has no attribute `__or__`']",
    "Line 67: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GenericTypeAlias2, type[list[Error]]]\"]",
    "Line 68: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[GenericTypeAlias2, type[list[Error]]]\"]"
  ],
  "aliases_type_statement.py": [
    "Line 26: Expected 1 errors",
    "Line 42: Expected 1 errors",
    "Line 43: Expected 1 errors",
    "Line 44: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 52: Expected 1 errors",
    "Line 58: Expected 1 errors",
    "Line 79: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 84: Expected 1 errors",
    "Line 86: Expected 1 errors",
    "Line 90: Expected 1 errors",
    "Line 82: Unexpected errors ['untype, got list[type[int] | type[str]]']"
  ],
  "aliases_typealiastype.py": [
    "Line 44: Expected 1 errors",
    "Line 46: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 52: Expected 1 errors",
    "Line 53: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 55: Expected 1 errors",
    "Line 56: Expected 1 errors",
    "Line 57: Expected 1 errors",
    "Line 58: Expected 1 errors",
    "Line 59: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 61: Expected 1 errors",
    "Line 62: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 64: Expected 1 errors",
    "Line 17: Unexpected errors ['EXPECTED tuple[type[TypeVar[T]]] <: tuple[ParamSpec | TypeVar | TypeVarTuple, ...]']",
    "Line 18: Unexpected errors ['EXPECTED tuple[type[TypeVar[S]], type[TypeVar[T]]] <: tuple[ParamSpec | TypeVar | TypeVarTuple, ...]']",
    "Line 19: Unexpected errors ['EXPECTED tuple[type[TypeVar[T]]] <: tuple[ParamSpec | TypeVar | TypeVarTuple, ...]']",
    "Line 23: Unexpected errors ['EXPECTED tuple[type[TypeVar[S]], type[TypeVar[TStr]], type[ParamSpec[P]], type[TypeVarTuple[Ts]]] <: tuple[ParamSpec | TypeVar | TypeVarTuple, ...]']",
    "Line 35: Unexpected errors ['untype, got GenericAlias']",
    "Line 36: Unexpected errors ['untype, got GenericAlias']",
    "Line 37: Unexpected errors ['untype, got GenericAlias']",
    "Line 38: Unexpected errors ['untype, got GenericAlias']",
    "Line 39: Unexpected errors ['untype, got GenericAlias', 'Expected an iterable, got type[tuple[int, str, int]]']"
  ],
  "aliases_variance.py": [
    "Line 24: Expected 1 errors",
    "Line 28: Expected 1 errors",
    "Line 44: Expected 1 errors"
  ],
  "annotations_coroutines.py": [],
  "annotations_forward_refs.py": [
    "Line 22: Expected 1 errors",
    "Line 23: Expected 1 errors",
    "Line 24: Expected 1 errors",
    "Line 25: Expected 1 errors",
    "Line 41: Expected 1 errors",
    "Line 46: Expected 1 errors",
    "Line 47: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 53: Expected 1 errors",
    "Line 66: Expected 1 errors",
    "Line 87: Unexpected errors ['untype, got (self: ClassD) -> None']",
    "Line 96: Unexpected errors ['assert_type(Any, int) failed']"
  ],
  "annotations_generators.py": [
    "Line 87: Expected 1 errors",
    "Line 92: Expected 1 errors",
    "Line 182: Unexpected errors ['assert_type(() -> AsyncIterator[int], () -> Coroutine[Any, Any, AsyncIterator[int]]) failed']",
    "Line 187: Unexpected errors ['EXPECTED None <: int']"
  ],
  "annotations_methods.py": [
    "Line 19: Unexpected errors ['Expected a callable, got type[?_TypeVar]']",
    "Line 23: Unexpected errors ['Expected a callable, got type[?_TypeVar]']"
  ],
  "annotations_typeexpr.py": [
    "Line 93: Expected 1 errors",
    "Line 94: Expected 1 errors",
    "Line 95: Expected 1 errors",
    "Line 100: Expected 1 errors"
  ],
  "callables_annotation.py": [
    "Line 56: Expected 1 errors",
    "Line 59: Expected 1 errors",
    "Line 51: Unexpected errors ['assert_type(int, tuple[int, ...]) failed']",
    "Line 52: Unexpected errors ['assert_type(int, dict[str, int]) failed']",
    "Line 90: Unexpected errors ['EXPECTED (x: int) -> str <: (int, ParamSpec(...)) -> str']",
    "Line 92: Unexpected errors ['EXPECTED (a: int, b: int, c: int) -> str <: (int, ParamSpec(...)) -> str']",
    "Line 151: Unexpected errors ['EXPECTED Proto2 <: (int, ParamSpec(...)) -> None']",
    "Line 155: Unexpected errors ['EXPECTED Proto3 <: Proto4[Ellipsis]']",
    "Line 156: Unexpected errors ['EXPECTED Proto4[Ellipsis] <: Proto3']",
    "Line 157: Unexpected errors ['EXPECTED Proto7 <: Proto6']",
    "Line 171: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[Callback1, type[(ParamSpec(ParamSpec[P])) -> str]]\"]",
    "Line 174: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[Callback1, type[(ParamSpec(ParamSpec[P])) -> str]]\"]",
    "Line 175: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[Callback2, type[(int, ParamSpec(ParamSpec[P])) -> str]]\"]",
    "Line 186: Unexpected errors ['EXPECTED (int, str) -> str <: (int, ParamSpec(...)) -> str']",
    "Line 188: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[CallbackWithInt, type[(int, ParamSpec(ParamSpec[P])) -> str]]\"]"
  ],
  "callables_kwargs.py": [
    "Line 101: Expected 1 errors",
    "Line 102: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 122: Expected 1 errors"
  ],
  "callables_protocol.py": [
    "Line 35: Expected 1 errors",
    "Line 36: Expected 1 errors",
    "Line 37: Expected 1 errors",
    "Line 67: Expected 1 errors",
    "Line 68: Expected 1 errors",
    "Line 69: Expected 1 errors",
    "Line 70: Expected 1 errors",
    "Line 260: Expected 1 errors",
    "Line 311: Expected 1 errors"
  ],
  "callables_subtyping.py": [
    "Line 211: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[TypeAliasWithP, type[(ParamSpec(ParamSpec[P])) -> None]]\"]",
    "Line 213: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[TypeAliasWithP, type[(ParamSpec(ParamSpec[P])) -> None]]\"]"
  ],
  "classes_classvar.py": [
    "Line 45: Expected 1 errors",
    "Line 46: Expected 1 errors",
    "Line 47: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 64: Expected 1 errors",
    "Line 67: Expected 1 errors",
    "Line 71: Expected 1 errors",
    "Line 105: Expected 1 errors",
    "Line 61: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `ClassVar[list[int]]`']"
  ],
  "classes_override.py": [
    "Lines 56, 65: Expected error (tag 'method4')"
  ],
  "constructors_call_init.py": [
    "Line 42: Expected 1 errors",
    "Line 107: Expected 1 errors",
    "Line 74: Unexpected errors ['assert_type(Class5[list[int]], Class5[set[str]]) failed', 'No matching overload found']",
    "Line 75: Unexpected errors ['assert_type(Class5[list[int]], Class5[float]) failed', 'No matching overload found']",
    "Line 91: Unexpected errors ['assert_type(Class6[TypeVar[V1], TypeVar[V2]], Class6[int, str]) failed']",
    "Line 92: Unexpected errors ['EXPECTED Class6[int, str] <: Class6[TypeVar[V1], TypeVar[V2]]']",
    "Line 99: Unexpected errors ['assert_type(Class7[TypeVar[V2], TypeVar[V1]], Class7[str, int]) failed']",
    "Line 100: Unexpected errors ['EXPECTED Class7[str, int] <: Class7[TypeVar[V2], TypeVar[V1]]']"
  ],
  "constructors_call_metaclass.py": [
    "Line 20: Unexpected errors ['EXPECTED object <: Class1', 'Expected 0 positional arguments, got 1']",
    "Line 23: Unexpected errors ['assert_type(Class1, NoReturn) failed', 'Missing argument `x`']",
    "Line 33: Unexpected errors ['EXPECTED object <: Class2', 'Expected 0 positional arguments, got 1']",
    "Line 43: Unexpected errors ['Object of class `super` has no attribute `__call__`']",
    "Line 48: Unexpected errors ['EXPECTED object <: Class3', 'Expected 0 positional arguments, got 1']",
    "Line 57: Unexpected errors ['Object of class `super` has no attribute `__call__`']",
    "Line 62: Unexpected errors ['EXPECTED object <: Class4', 'Expected 0 positional arguments, got 1']"
  ],
  "constructors_call_new.py": [
    "Line 16: Unexpected errors ['EXPECTED object <: Class1[?_TypeVar]', 'Expected 0 positional arguments, got 1']",
    "Line 29: Unexpected errors ['EXPECTED object <: Class2[?_TypeVar]', 'Expected 0 positional arguments, got 1']",
    "Line 64: Unexpected errors ['assert_type(Class4, Class4 | Any) failed', 'Missing argument `x`']",
    "Line 76: Unexpected errors ['assert_type(Class5, NoReturn) failed', 'Missing argument `x`']",
    "Line 98: Unexpected errors ['Expected 0 positional arguments, got 1']",
    "Line 104: Unexpected errors ['assert_type(object, Class7) failed']"
  ],
  "constructors_call_type.py": [
    "Line 25: Unexpected errors ['EXPECTED object <: Class1']",
    "Line 35: Unexpected errors ['EXPECTED object <: Class2', 'Expected 0 positional arguments, got 1']",
    "Line 63: Unexpected errors ['Expected a callable, got type[?_TypeVar]']",
    "Line 71: Unexpected errors ['Expected a callable, got type[?_TypeVar]']",
    "Line 79: Unexpected errors ['Expected a callable, got type[?_TypeVar]']",
    "Line 80: Unexpected errors ['Expected a callable, got type[?_TypeVar]']"
  ],
  "constructors_callable.py": [
    "Line 35: Unexpected errors ['EXPECTED type[Class1] <: (ParamSpec(@_)) -> @_']",
    "Line 36: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 37: Unexpected errors ['assert_type(Any, Class1) failed', 'Unexpected ParamSpec type']",
    "Line 48: Unexpected errors ['EXPECTED type[Class2] <: (ParamSpec(@_)) -> @_']",
    "Line 49: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 50: Unexpected errors ['assert_type(Any, Class2) failed', 'Unexpected ParamSpec type']",
    "Line 62: Unexpected errors ['EXPECTED type[Class3] <: (ParamSpec(@_)) -> @_']",
    "Line 63: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 64: Unexpected errors ['assert_type(Any, Class3) failed', 'Unexpected ParamSpec type']",
    "Line 76: Unexpected errors ['EXPECTED type[Class4] <: (ParamSpec(@_)) -> @_']",
    "Line 77: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 78: Unexpected errors ['assert_type(Any, int) failed', 'Unexpected ParamSpec type']",
    "Line 93: Unexpected errors ['EXPECTED object <: Class5', 'Expected 0 positional arguments, got 1']",
    "Line 96: Unexpected errors ['EXPECTED type[Class5] <: (ParamSpec(@_)) -> @_']",
    "Line 97: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 100: Unexpected errors ['assert_type(Any, NoReturn) failed', 'Unexpected ParamSpec type']",
    "Line 105: Unexpected errors ['assert_type(Any, NoReturn) failed', 'Unexpected ParamSpec type']",
    "Line 124: Unexpected errors ['EXPECTED type[Class6] <: (ParamSpec(@_)) -> @_']",
    "Line 125: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 126: Unexpected errors ['assert_type(Any, Class6Proxy) failed', 'Unexpected ParamSpec type']",
    "Line 134: Unexpected errors ['Expected 0 positional arguments, got 1']",
    "Line 141: Unexpected errors ['EXPECTED type[Class6Any] <: (ParamSpec(@_)) -> @_']",
    "Line 142: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 143: Unexpected errors ['Unexpected ParamSpec type']",
    "Line 160: Unexpected errors ['EXPECTED type[Class7] <: (ParamSpec(@_)) -> @_']",
    "Line 161: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 164: Unexpected errors ['assert_type(Any, Class7[int]) failed', 'Unexpected ParamSpec type']",
    "Line 165: Unexpected errors ['assert_type(Any, Class7[str]) failed', 'Unexpected ParamSpec type']",
    "Line 178: Unexpected errors ['EXPECTED object <: Class8[?_TypeVar]', 'Expected 0 positional arguments, got 1']",
    "Line 181: Unexpected errors ['EXPECTED type[Class8] <: (ParamSpec(@_)) -> @_']",
    "Line 182: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 183: Unexpected errors ['assert_type(Any, Class8[str]) failed', 'Unexpected ParamSpec type']",
    "Line 192: Unexpected errors ['EXPECTED type[Class9] <: (ParamSpec(@_)) -> @_']",
    "Line 193: Unexpected errors ['revealed type: (ParamSpec(Unknown)) -> Unknown']",
    "Line 194: Unexpected errors ['assert_type(Any, Class9) failed', 'Unexpected ParamSpec type']"
  ],
  "constructors_consistency.py": [
    "Line 22: Unexpected errors ['EXPECTED object <: Class1', 'Expected 0 positional arguments, got 1']"
  ],
  "dataclasses_descriptors.py": [
    "Line 35: Unexpected errors ['EXPECTED Literal[3] <: Desc1']",
    "Line 37: Unexpected errors ['assert_type(Desc1, int) failed']",
    "Line 61: Unexpected errors ['assert_type(Any, list[int]) failed', 'Instance-only attribute `x` of class `DC2` is not visible on the class']",
    "Line 62: Unexpected errors ['assert_type(Any, list[str]) failed', 'Instance-only attribute `y` of class `DC2` is not visible on the class']",
    "Line 63: Unexpected errors ['assert_type(Desc2[str], list[str]) failed']",
    "Line 66: Unexpected errors ['assert_type(Desc2[int], int) failed']",
    "Line 67: Unexpected errors ['assert_type(Desc2[str], str) failed']",
    "Line 68: Unexpected errors ['assert_type(Desc2[str], str) failed']"
  ],
  "dataclasses_final.py": [
    "Line 27: Expected 1 errors",
    "Line 35: Expected 1 errors",
    "Line 36: Expected 1 errors",
    "Line 38: Expected 1 errors"
  ],
  "dataclasses_frozen.py": [
    "Lines 22, 23: Expected error (tag 'DC2')",
    "Lines 32, 33: Expected error (tag 'DC4')"
  ],
  "dataclasses_hash.py": [],
  "dataclasses_inheritance.py": [
    "Line 60: Expected 1 errors",
    "Line 64: Expected 1 errors"
  ],
  "dataclasses_kwonly.py": [
    "Line 32: Unexpected errors ['Missing argument `a`', 'Expected 0 positional arguments, got 1']",
    "Line 35: Unexpected errors ['Missing argument `a`', 'Expected 0 positional arguments, got 1']",
    "Line 47: Unexpected errors ['Missing argument `a`', 'Expected 0 positional arguments, got 1']",
    "Line 50: Unexpected errors ['Missing argument `a`', 'Expected 0 positional arguments, got 1']",
    "Line 61: Unexpected errors ['Missing argument `c`', 'EXPECTED float <: int', 'Multiple values for argument `b`']"
  ],
  "dataclasses_order.py": [],
  "dataclasses_postinit.py": [
    "Line 19: Expected 1 errors",
    "Line 28: Expected 1 errors",
    "Line 29: Expected 1 errors",
    "Line 36: Expected 1 errors",
    "Line 23: Unexpected errors ['EXPECTED Literal[3] <: InitVar[int]', \"EXPECTED Literal[''] <: InitVar[str]\"]"
  ],
  "dataclasses_slots.py": [
    "Line 25: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Lines 10, 11: Expected error (tag 'DC1')",
    "Line 56: Unexpected errors ['Class `DC5` has no class attribute `__slots__`']",
    "Line 57: Unexpected errors ['Object of class `DC5` has no attribute `__slots__`']"
  ],
  "dataclasses_transform_class.py": [
    "Line 51: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 122: Expected 1 errors",
    "Line 60: Unexpected errors ['Missing argument `not_a_field`', 'Unexpected keyword argument `id`', 'Unexpected keyword argument `name`', 'Unexpected keyword argument `other_name`']",
    "Line 68: Unexpected errors ['Missing argument `not_a_field`', 'Unexpected keyword argument `id`', 'Unexpected keyword argument `name`']",
    "Line 74: Unexpected errors ['Missing argument `not_a_field`', 'Unexpected keyword argument `id`', 'Unexpected keyword argument `name`']",
    "Line 76: Unexpected errors ['Missing argument `not_a_field`', 'Unexpected keyword argument `id`']",
    "Line 78: Unexpected errors ['`<` not supported between `Customer2` and `Customer2`']",
    "Line 106: Unexpected errors ['Unexpected keyword argument `id`']",
    "Line 119: Unexpected errors ['Unexpected keyword argument `id`', 'Unexpected keyword argument `name`']"
  ],
  "dataclasses_transform_converter.py": [
    "Line 118: Expected 1 errors",
    "Line 29: Unexpected errors ['EXPECTED tuple[Forall[S, T, (*, converter: (S) -> T, default: S | None, default_factory: () -> S | None) -> T]] <: tuple[(...) -> Any | type[Any], ...]']",
    "Line 102: Unexpected errors ['EXPECTED type[ConverterClass] <: (@_) -> @_']",
    "Line 104: Unexpected errors ['EXPECTED type[dict] <: (@_) -> @_']",
    "Line 112: Unexpected errors ['Expected 0 positional arguments, got 5']",
    "Line 114: Unexpected errors [\"EXPECTED Literal['f1'] <: int\"]",
    "Line 115: Unexpected errors [\"EXPECTED Literal['f6'] <: ConverterClass\"]",
    "Line 116: Unexpected errors [\"EXPECTED Literal[b'f6'] <: ConverterClass\"]",
    "Line 121: Unexpected errors ['Expected 0 positional arguments, got 6']",
    "Line 132: Unexpected errors ['EXPECTED type[str] <: () -> str | None']"
  ],
  "dataclasses_transform_field.py": [
    "Line 60: Unexpected errors ['Unexpected keyword argument `name`']",
    "Line 77: Unexpected errors ['Unexpected keyword argument `name`']"
  ],
  "dataclasses_transform_func.py": [
    "Line 97: Expected 1 errors",
    "Lines 89, 90: Expected error (tag 'Customer3Subclass')",
    "Line 50: Unexpected errors ['Unexpected keyword argument `id`', 'Unexpected keyword argument `name`']",
    "Line 53: Unexpected errors ['Expected 0 positional arguments, got 2']",
    "Line 67: Unexpected errors ['Unexpected keyword argument `id`', 'Unexpected keyword argument `name`']",
    "Line 73: Unexpected errors ['`<` not supported between `Customer2` and `Customer2`']",
    "Line 94: Unexpected errors ['Unexpected keyword argument `id`', 'Unexpected keyword argument `name`']"
  ],
  "dataclasses_transform_meta.py": [
    "Line 51: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 103: Expected 1 errors",
    "Line 60: Unexpected errors ['Unexpected keyword argument `id`', 'Unexpected keyword argument `name`', 'Unexpected keyword argument `other_name`']",
    "Line 69: Unexpected errors ['Unexpected keyword argument `id`', 'Unexpected keyword argument `name`']",
    "Line 75: Unexpected errors ['Unexpected keyword argument `id`', 'Unexpected keyword argument `name`']",
    "Line 77: Unexpected errors ['Unexpected keyword argument `id`']",
    "Line 79: Unexpected errors ['`<` not supported between `Customer2` and `Customer2`']",
    "Line 100: Unexpected errors ['Unexpected keyword argument `id`', 'Unexpected keyword argument `name`']"
  ],
  "dataclasses_usage.py": [
    "Lines 58, 61: Expected error (tag 'DC1')",
    "Lines 64, 67: Expected error (tag 'DC2')",
    "Lines 70, 73: Expected error (tag 'DC3')",
    "Line 35: Unexpected errors ['EXPECTED BoundMethod[InventoryItem, (self: InventoryItem, name: str, unit_price: float, quantity_on_hand: int) -> None] <: InventoryItemInitProto']",
    "Line 72: Unexpected errors ['EXPECTED Literal[0] <: InitVar[int]']",
    "Line 106: Unexpected errors ['assert_type(BoundMethod[DC6, (str) -> int], (str) -> int) failed']",
    "Line 205: Unexpected errors ['EXPECTED DC15 <: DataclassProto']"
  ],
  "directives_assert_type.py": [
    "Line 24: Unexpected errors ['assert_type(ForwardReference, Any) failed', \"untype, got Literal['ForwardReference']\"]"
  ],
  "directives_cast.py": [
    "Line 16: Expected 1 errors"
  ],
  "directives_deprecated.py": [
    "Line 18: Expected 1 errors",
    "Line 24: Expected 1 errors",
    "Line 25: Expected 1 errors",
    "Line 30: Expected 1 errors",
    "Line 41: Expected 1 errors",
    "Line 44: Expected 1 errors",
    "Line 47: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 58: Expected 1 errors",
    "Line 69: Expected 1 errors",
    "Line 98: Expected 1 errors"
  ],
  "directives_no_type_check.py": [],
  "directives_reveal_type.py": [
    "Line 14: Unexpected errors ['revealed type: int | str']",
    "Line 15: Unexpected errors ['revealed type: list[int]']",
    "Line 16: Unexpected errors ['revealed type: Any']",
    "Line 17: Unexpected errors ['revealed type: ForwardReference']"
  ],
  "directives_type_checking.py": [
    "Line 11: Unexpected errors [\"EXPECTED Literal[''] <: int\"]",
    "Line 16: Unexpected errors ['Inconsistent type annotations for b: list[str], list[int]']",
    "Line 18: Unexpected errors ['assert_type(list[int] | list[str], list[int]) failed']"
  ],
  "directives_type_ignore.py": [],
  "directives_type_ignore_file1.py": [
    "Line 16: Unexpected errors [\"EXPECTED Literal[''] <: int\"]"
  ],
  "directives_type_ignore_file2.py": [],
  "directives_version_platform.py": [],
  "enums_behaviors.py": [
    "Line 39: Expected 1 errors",
    "Line 19: Unexpected errors ['EXPECTED EnumMeta <: type[@_]', 'EXPECTED int <: str']",
    "Line 20: Unexpected errors ['assert_type(Any, Color) failed']",
    "Line 26: Unexpected errors ['assert_type(type[Color], Color) failed', 'Expected 0 type arguments for class `Color`, got 1.', \"untype, got Literal['RED']\"]",
    "Line 27: Unexpected errors ['assert_type(Enum, Color) failed']"
  ],
  "enums_definition.py": [],
  "enums_expansion.py": [],
  "enums_member_names.py": [],
  "enums_member_values.py": [],
  "enums_members.py": [
    "Line 27: Unexpected errors ['assert_type(Any, str) failed', 'Instance-only attribute `genus` of class `Pet` is not visible on the class']",
    "Line 28: Unexpected errors ['assert_type(Any, str) failed', 'Instance-only attribute `species` of class `Pet` is not visible on the class']",
    "Line 35: Unexpected errors ['assert_type(Any, str) failed', 'Instance-only attribute `genus` of class `Pet2` is not visible on the class']",
    "Line 36: Unexpected errors ['assert_type(Any, str) failed', 'Instance-only attribute `species` of class `Pet2` is not visible on the class']",
    "Line 100: Unexpected errors ['assert_type(Literal[TrafficLight.AMBER], Literal[TrafficLight.YELLOW]) failed']",
    "Line 128: Unexpected errors ['Could not find name `reveal_type`', 'revealed type: int']"
  ],
  "exceptions_context_managers.py": [
    "Line 50: Unexpected errors ['assert_type(str, int | str) failed']",
    "Line 57: Unexpected errors ['assert_type(str, int | str) failed']"
  ],
  "generics_base_class.py": [
    "Line 30: Expected 1 errors",
    "Line 68: Expected 1 errors"
  ],
  "generics_basic.py": [
    "Line 49: Expected 1 errors",
    "Line 55: Expected 1 errors",
    "Line 121: Expected 1 errors",
    "Line 191: Expected 1 errors",
    "Line 34: Unexpected errors ['TODO: Expr::attr_infer attribute base undefined for type: ?_TypeVar (trying to access __add__)']",
    "Line 67: Unexpected errors ['assert_type(MyStr, str) failed']",
    "Line 68: Unexpected errors ['assert_type(MyStr, str) failed', 'EXPECTED str <: MyStr']"
  ],
  "generics_defaults.py": [
    "Line 104: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 45: Unexpected errors ['assert_type(type[AllTheDefaults[Error, Error, str, int, bool]], type[AllTheDefaults[Any, Any, str, int, bool]]) failed']",
    "Line 76: Unexpected errors ['untype, got ParamSpec']",
    "Line 79: Unexpected errors ['Expected 0 type arguments for class `Class_ParamSpec`, got 2.']",
    "Line 80: Unexpected errors ['Expected 0 type arguments for class `Class_ParamSpec`, got 2.']",
    "Line 81: Unexpected errors ['Expected 0 type arguments for class `Class_ParamSpec`, got 1.', 'untype, got list[type[bool]]', 'Expected 0 type arguments for class `Class_ParamSpec`, got 2.']",
    "Line 91: Unexpected errors ['untype, got TypeVarTuple']",
    "Line 94: Unexpected errors ['Expected 0 type arguments for class `Class_TypeVarTuple`, got 1.']",
    "Line 95: Unexpected errors ['Expected 0 type arguments for class `Class_TypeVarTuple`, got 2.']",
    "Line 96: Unexpected errors ['Expected 0 type arguments for class `Class_TypeVarTuple`, got 2.', 'Expected 0 type arguments for class `Class_TypeVarTuple`, got 2.']",
    "Line 127: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 148: Unexpected errors ['untype, got ParamSpec']",
    "Line 151: Unexpected errors ['assert_type(type[Foo6[tuple[int, str]]], type[Foo6[tuple[int, str, Any]]]) failed', 'untype, got list[type[bool] | type[float]]']",
    "Line 152: Unexpected errors ['untype, got list[type[bytes]]', 'untype, got list[type[bytes]]']",
    "Line 166: Unexpected errors ['assert_type(Any, (Foo7[int]) -> Foo7[int]) failed', 'Generic attribute `meth` of class `Foo7` is not visible on the class']",
    "Line 167: Unexpected errors ['assert_type(Any, int) failed', 'Instance-only attribute `attr` of class `Foo7` is not visible on the class']"
  ],
  "generics_defaults_referential.py": [
    "Line 53: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 68: Expected 1 errors",
    "Line 74: Expected 1 errors",
    "Line 78: Expected 1 errors",
    "Line 23: Unexpected errors ['assert_type(type[slice[int, TypeVar[StartT], int | None]], type[slice[int, int, int | None]]) failed']",
    "Line 24: Unexpected errors ['assert_type(slice[Any, Any, Any], slice[int, int, int | None]) failed']",
    "Line 25: Unexpected errors ['assert_type(slice[str, TypeVar[StartT], int | None], slice[str, str, int | None]) failed']",
    "Line 94: Unexpected errors ['assert_type(type[Bar[Error, list[TypeVar[Z1]]]], type[Bar[Any, list[Any]]]) failed']",
    "Line 95: Unexpected errors ['assert_type(type[Bar[int, list[TypeVar[Z1]]]], type[Bar[int, list[int]]]) failed']",
    "Line 96: Unexpected errors ['assert_type(Bar[int, list[TypeVar[Z1]]], Bar[int, list[int]]) failed']"
  ],
  "generics_defaults_specialization.py": [
    "Line 30: Expected 1 errors",
    "Line 25: Unexpected errors ['untype, got Forall[DefaultStrT, LegacyExplicitTypeAlias[MyAlias, type[SomethingWithNoDefaults[int, DefaultStrT]]]]']",
    "Line 26: Unexpected errors ['assert_type(Any, SomethingWithNoDefaults[int, str]) failed']",
    "Line 46: Unexpected errors ['assert_type(Bar[Any], Bar[str]) failed']"
  ],
  "generics_paramspec_basic.py": [
    "Line 15: Expected 1 errors",
    "Line 23: Expected 1 errors",
    "Line 27: Expected 1 errors",
    "Line 31: Expected 1 errors",
    "Line 35: Expected 1 errors",
    "Line 39: Expected 1 errors"
  ],
  "generics_paramspec_components.py": [
    "Line 17: Expected 1 errors",
    "Line 20: Expected 1 errors",
    "Line 23: Expected 1 errors",
    "Line 26: Expected 1 errors",
    "Line 30: Expected 1 errors",
    "Line 35: Expected 1 errors",
    "Line 36: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 41: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 96: Unexpected errors ['EXPECTED (a: int, b: str) -> int <: (*Unknown, **Unknown) -> int']",
    "Line 97: Unexpected errors ['EXPECTED (a: int, b: str) -> int <: (*Unknown, **Unknown) -> int']"
  ],
  "generics_paramspec_semantics.py": [
    "Line 22: Unexpected errors ['assert_type((str, bool) -> str, (str, bool) -> str) failed']",
    "Line 82: Unexpected errors ['assert_type(Y[int, (int)], Y[int, Any]) failed', 'untype, got list[type[int]]']",
    "Line 84: Unexpected errors ['assert_type((int) -> str, (int) -> str) failed']"
  ],
  "generics_paramspec_specialization.py": [
    "Line 44: Expected 1 errors",
    "Line 32: Unexpected errors ['untype, got list[type[bool] | type[int]]']",
    "Line 40: Unexpected errors ['untype, got list[@_]', 'untype, got list[@_]']",
    "Line 52: Unexpected errors ['untype, got list[type[bool] | type[int] | type[str]]']",
    "Line 53: Unexpected errors ['Unexpected ParamSpec type']",
    "Line 58: Unexpected errors ['Expected 1 type argument for class `ClassC`, got 3.']",
    "Line 59: Unexpected errors ['Unexpected ParamSpec type']"
  ],
  "generics_scoping.py": [
    "Line 50: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 75: Expected 1 errors",
    "Line 78: Expected 1 errors",
    "Line 87: Expected 1 errors",
    "Line 94: Expected 1 errors",
    "Line 95: Expected 1 errors",
    "Line 96: Expected 1 errors"
  ],
  "generics_self_advanced.py": [
    "Line 19: Unexpected errors ['assert_type(ParentA, ChildA) failed']",
    "Line 35: Unexpected errors ['assert_type(ChildB, Self) failed']",
    "Line 38: Unexpected errors ['assert_type(ParentB, Self) failed', 'EXPECTED type[ChildB] <: ParentB']",
    "Line 42: Unexpected errors ['assert_type(ChildB, type[Self]) failed']",
    "Line 45: Unexpected errors ['assert_type(ParentB, Self) failed', 'EXPECTED type[ChildB] <: ParentB']"
  ],
  "generics_self_attributes.py": [
    "Line 29: Unexpected errors ['EXPECTED OrdinalLinkedList <: Self | None']"
  ],
  "generics_self_basic.py": [
    "Line 20: Expected 1 errors",
    "Line 33: Expected 1 errors",
    "Line 14: Unexpected errors ['assert_type(Shape, Self) failed']",
    "Line 15: Unexpected errors ['Object of class `Shape` has no attribute `scale`']",
    "Line 27: Unexpected errors ['assert_type(Shape, type[Self]) failed']",
    "Line 28: Unexpected errors ['Expected a callable, got Shape']",
    "Line 37: Unexpected errors ['Expected a callable, got Shape']",
    "Line 40: Unexpected errors ['assert_type(Shape, Self) failed']",
    "Line 52: Unexpected errors ['assert_type(Shape, Circle) failed']",
    "Line 54: Unexpected errors ['EXPECTED type[Shape] <: Shape']",
    "Line 55: Unexpected errors ['assert_type(Shape, Circle) failed', 'EXPECTED type[Circle] <: Shape']"
  ],
  "generics_self_protocols.py": [
    "Line 64: Expected 1 errors"
  ],
  "generics_self_usage.py": [
    "Line 73: Expected 1 errors",
    "Line 76: Expected 1 errors",
    "Line 82: Expected 1 errors",
    "Line 86: Expected 1 errors",
    "Line 101: Expected 1 errors",
    "Line 103: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 111: Expected 1 errors",
    "Line 116: Expected 1 errors",
    "Line 121: Expected 1 errors",
    "Line 125: Expected 1 errors",
    "Line 15: Unexpected errors ['Expected a callable, got ReturnsSelf']",
    "Line 30: Unexpected errors ['EXPECTED ReturnsSelf <: type[ReturnsSelf]']",
    "Line 50: Unexpected errors ['EXPECTED (self: CallableAttribute) -> int <: (Self) -> int']",
    "Line 60: Unexpected errors ['TODO: Expr::attr_infer attribute base undefined for type: Self (trying to access x)']",
    "Line 63: Unexpected errors ['EXPECTED HasNestedFunction <: Self']",
    "Line 93: Unexpected errors ['Object of class `Foo3` has no attribute `child_value`']"
  ],
  "generics_syntax_compatibility.py": [],
  "generics_syntax_declarations.py": [
    "Line 46: Expected 1 errors",
    "Line 62: Expected 1 errors",
    "Line 66: Expected 1 errors",
    "Line 14: Unexpected errors ['assert_type(type[?_TypeVar], TypeVar) failed']",
    "Line 15: Unexpected errors ['assert_type(type[?_TypeVarTuple], TypeVarTuple) failed']",
    "Line 16: Unexpected errors ['assert_type(type[?_ParamSpec], ParamSpec) failed']",
    "Line 33: Unexpected errors ['TODO: Expr::attr_infer attribute base undefined for type: ?_TypeVar (trying to access capitalize)']"
  ],
  "generics_syntax_infer_variance.py": [
    "Line 28: Unexpected errors ['EXPECTED ShouldBeCovariant1[int] <: ShouldBeCovariant1[float]']",
    "Line 36: Unexpected errors ['EXPECTED ShouldBeCovariant2[int] <: ShouldBeCovariant2[float]']",
    "Line 45: Unexpected errors ['EXPECTED ShouldBeCovariant3[int] <: ShouldBeCovariant3[float]']",
    "Line 54: Unexpected errors ['EXPECTED ShouldBeCovariant4[int] <: ShouldBeCovariant4[float]']",
    "Line 67: Unexpected errors ['EXPECTED ShouldBeCovariant5[int] <: ShouldBeCovariant5[float]']",
    "Line 78: Unexpected errors ['EXPECTED ShouldBeCovariant6[int] <: ShouldBeCovariant6[float]']",
    "Line 149: Unexpected errors ['EXPECTED ShouldBeContravariant1[float] <: ShouldBeContravariant1[int]']"
  ],
  "generics_syntax_scoping.py": [
    "Line 14: Expected 1 errors",
    "Line 35: Expected 1 errors",
    "Line 92: Expected 1 errors",
    "Line 95: Expected 1 errors",
    "Line 98: Expected 1 errors",
    "Line 61: Unexpected errors ['TODO: StmtNonlocal - Bindings::stmt']",
    "Line 66: Unexpected errors ['TODO: StmtGlobal - Bindings::stmt']",
    "Line 67: Unexpected errors ['assert_type(str, int) failed']",
    "Line 116: Unexpected errors ['assert_type(type[?_TypeVar], TypeVar) failed']"
  ],
  "generics_type_erasure.py": [
    "Line 56: Unexpected errors ['assert_type(Any, bytes) failed']"
  ],
  "generics_typevartuple_args.py": [
    "Line 20: Unexpected errors ['assert_type(tuple[*Any], tuple[int, str]) failed', 'EXPECTED Literal[1] <: *@_', \"EXPECTED Literal['a'] <: *@_\"]",
    "Line 31: Unexpected errors ['assert_type(tuple[*Any], tuple[()]) failed', 'EXPECTED Env <: *tuple[*@_, Env]']",
    "Line 32: Unexpected errors ['assert_type(tuple[*Any], tuple[int, str]) failed', 'EXPECTED Literal[0] <: *tuple[*@_, Env]', \"EXPECTED Literal[''] <: *tuple[*@_, Env]\", 'EXPECTED Env <: *tuple[*@_, Env]']",
    "Line 47: Unexpected errors ['EXPECTED Literal[1] <: *tuple[int, ...]', 'EXPECTED Literal[2] <: *tuple[int, ...]', 'EXPECTED Literal[3] <: *tuple[int, ...]', 'EXPECTED Literal[4] <: *tuple[int, ...]', 'EXPECTED Literal[5] <: *tuple[int, ...]']",
    "Line 55: Unexpected errors ['EXPECTED Literal[1] <: *tuple[int, *tuple[str, ...], str]', \"EXPECTED Literal[''] <: *tuple[int, *tuple[str, ...], str]\"]",
    "Line 56: Unexpected errors ['EXPECTED Literal[1] <: *tuple[int, *tuple[str, ...], str]', \"EXPECTED Literal[''] <: *tuple[int, *tuple[str, ...], str]\", \"EXPECTED Literal[''] <: *tuple[int, *tuple[str, ...], str]\", \"EXPECTED Literal[''] <: *tuple[int, *tuple[str, ...], str]\", \"EXPECTED Literal[''] <: *tuple[int, *tuple[str, ...], str]\"]",
    "Line 66: Unexpected errors ['EXPECTED Literal[1] <: *tuple[int, str]', \"EXPECTED Literal['hello'] <: *tuple[int, str]\"]"
  ],
  "generics_typevartuple_basic.py": [
    "Line 52: Expected 1 errors",
    "Line 59: Expected 1 errors",
    "Line 99: Expected 1 errors",
    "Line 36: Unexpected errors ['untype, got NewType', 'untype, got NewType']",
    "Line 37: Unexpected errors ['untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 38: Unexpected errors ['untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 85: Unexpected errors ['EXPECTED tuple[float] <: tuple[*tuple[int]]']",
    "Line 97: Unexpected errors ['untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType']"
  ],
  "generics_typevartuple_callable.py": [
    "Line 25: Unexpected errors ['EXPECTED (arg1: int, arg2: str) -> None <: (*@_) -> None']",
    "Line 41: Unexpected errors ['EXPECTED (a: int, b: str, c: int, d: complex) -> tuple[complex, str, int] <: (int, *tuple[str, int], complex) -> tuple[complex, *tuple[str, int]]']",
    "Line 42: Unexpected errors ['EXPECTED (a: int, d: str) -> tuple[str] <: (int, *tuple[()], str) -> tuple[str, *tuple[()]]']",
    "Line 49: Unexpected errors ['assert_type(tuple[Any, *Any], tuple[float, str, complex]) failed', 'EXPECTED Literal[1] <: *tuple[int, *@_, @_]', \"EXPECTED Literal[''] <: *tuple[int, *@_, @_]\", 'EXPECTED complex <: *tuple[int, *@_, @_]', 'EXPECTED float <: *tuple[int, *@_, @_]']"
  ],
  "generics_typevartuple_concat.py": [
    "Line 26: Unexpected errors ['untype, got NewType']",
    "Line 30: Unexpected errors ['untype, got NewType']",
    "Line 34: Unexpected errors ['untype, got NewType', 'untype, got NewType']",
    "Line 38: Unexpected errors ['untype, got NewType', 'untype, got NewType']",
    "Line 40: Unexpected errors ['untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 42: Unexpected errors ['untype, got NewType', 'untype, got NewType']",
    "Line 44: Unexpected errors ['untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 56: Unexpected errors ['EXPECTED tuple[*tuple[Unknown, ...], Unknown] <: tuple[*?_TypeVarTuple, ?_TypeVar]']"
  ],
  "generics_typevartuple_overloads.py": [
    "Line 30: Unexpected errors ['assert_type(Any, Array[tuple[?_TypeVar, ?_TypeVar]]) failed', 'No matching overload found']",
    "Line 31: Unexpected errors ['assert_type(Any, Array[tuple[?_TypeVar, ?_TypeVar, ?_TypeVar]]) failed', 'No matching overload found']"
  ],
  "generics_typevartuple_specialization.py": [
    "Line 28: Unexpected errors ['untype, got NewType', 'untype, got NewType']",
    "Line 33: Unexpected errors ['untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 45: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[IntTuple, type[tuple[int, *TypeVarTuple[Ts]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[NamedArray, type[tuple[str, Array[tuple[*TypeVarTuple[Ts]]]]]]\"]",
    "Line 46: Unexpected errors ['assert_type(Any, tuple[int, float, bool]) failed']",
    "Line 47: Unexpected errors ['assert_type(Any, tuple[str, Array[tuple[Any]]]) failed', 'untype, got NewType']",
    "Line 50: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[IntTuple, type[tuple[int, *TypeVarTuple[Ts]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[NamedArray, type[tuple[str, Array[tuple[*TypeVarTuple[Ts]]]]]]\"]",
    "Line 51: Unexpected errors ['assert_type(Any, tuple[int]) failed']",
    "Line 52: Unexpected errors ['assert_type(Any, tuple[str, Array[tuple[Any, ...]]]) failed']",
    "Line 59: Unexpected errors ['Class `Array2` uses type variables not specified in `Generic` or `Protocol` base']",
    "Line 67: Unexpected errors ['untype, got Forall[DType, LegacyImplicitTypeAlias[Array1D, type[Array2[DType, tuple[Any]]]]]']",
    "Line 68: Unexpected errors ['assert_type(Any, Array2[Any, tuple[Any]]) failed']",
    "Line 76: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[FloatArray, type[Array2[float, tuple[*TypeVarTuple[Shape]]]]]\"]",
    "Line 80: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[FloatArray, type[Array2[float, tuple[*TypeVarTuple[Shape]]]]]\"]",
    "Line 92: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[VariadicTuple, type[tuple[TypeVar[T], *TypeVarTuple[Ts]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[VariadicTuple, type[tuple[TypeVar[T], *TypeVarTuple[Ts]]]]\"]",
    "Line 93: Unexpected errors ['assert_type(Any, tuple[str, int]) failed']",
    "Line 94: Unexpected errors ['assert_type(Any, tuple[float]) failed']",
    "Line 95: Unexpected errors ['assert_type(tuple[TypeVar[T], *TypeVarTuple[Ts]], tuple[Any, *tuple[Any, ...]]) failed']",
    "Line 102: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[IntTupleVar, type[tuple[int, *TypeVarTuple[Ts1]]]]\"]",
    "Line 103: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[IntTupleVar, type[tuple[int, *TypeVarTuple[Ts1]]]]\"]",
    "Line 108: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[IntTupleGeneric, type[tuple[int, TypeVar[T]]]]\"]",
    "Line 130: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA7, type[tuple[*TypeVarTuple[Ts], TypeVar[T1], TypeVar[T2]]]]\"]",
    "Line 134: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA7, type[tuple[*TypeVarTuple[Ts], TypeVar[T1], TypeVar[T2]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA7, type[tuple[*TypeVarTuple[Ts], TypeVar[T1], TypeVar[T2]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA7, type[tuple[*TypeVarTuple[Ts], TypeVar[T1], TypeVar[T2]]]]\"]",
    "Line 135: Unexpected errors ['assert_type(tuple[tuple[*Any], Any, Any], tuple[tuple[()], str, bool]) failed']",
    "Line 136: Unexpected errors ['assert_type(tuple[tuple[*Any], Any, Any], tuple[tuple[str], bool, float]) failed']",
    "Line 137: Unexpected errors ['assert_type(tuple[tuple[*Any], Any, Any], tuple[tuple[str, bool], float, int]) failed']",
    "Line 143: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA8, type[tuple[TypeVar[T1], *TypeVarTuple[Ts], TypeVar[T2], TypeVar[T3]]]]\"]",
    "Line 147: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA8, type[tuple[TypeVar[T1], *TypeVarTuple[Ts], TypeVar[T2], TypeVar[T3]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA8, type[tuple[TypeVar[T1], *TypeVarTuple[Ts], TypeVar[T2], TypeVar[T3]]]]\"]",
    "Line 148: Unexpected errors ['assert_type(tuple[tuple[*Any], Any, Any, Any], tuple[tuple[()], str, bool, float]) failed']",
    "Line 149: Unexpected errors ['assert_type(tuple[tuple[*Any], Any, Any, Any], tuple[tuple[bool], str, float, int]) failed']",
    "Line 153: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA9, type[tuple[*TypeVarTuple[Ts], TypeVar[T1]]]]\"]",
    "Line 156: Unexpected errors [\"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA9, type[tuple[*TypeVarTuple[Ts], TypeVar[T1]]]]\", \"Can't apply arguments to non-class, got LegacyImplicitTypeAlias[TA9, type[tuple[*TypeVarTuple[Ts], TypeVar[T1]]]]\"]",
    "Line 157: Unexpected errors ['assert_type(Any, tuple[*tuple[int, ...], int]) failed']",
    "Line 158: Unexpected errors ['assert_type(Any, tuple[*tuple[int, ...], str]) failed']",
    "Line 159: Unexpected errors ['assert_type(Any, tuple[*tuple[int, ...], str]) failed']"
  ],
  "generics_typevartuple_unpack.py": [
    "Line 21: Unexpected errors ['untype, got NewType', 'untype, got NewType']",
    "Line 26: Unexpected errors ['untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType']",
    "Line 36: Unexpected errors ['untype, got NewType']",
    "Line 40: Unexpected errors ['untype, got NewType', 'untype, got NewType', 'untype, got NewType', 'untype, got NewType']"
  ],
  "generics_upper_bound.py": [
    "Line 24: Expected 1 errors",
    "Line 51: Expected 1 errors",
    "Line 31: Unexpected errors ['EXPECTED ?_TypeVar <: Sized', 'EXPECTED ?_TypeVar <: Sized']"
  ],
  "generics_variance.py": [
    "Line 77: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 93: Expected 1 errors",
    "Line 105: Expected 1 errors",
    "Line 113: Expected 1 errors",
    "Line 163: Expected 1 errors",
    "Line 167: Expected 1 errors",
    "Line 191: Expected 1 errors",
    "Lines 125, 126: Expected error (tag 'CoContra_Child2')",
    "Lines 131, 132: Expected error (tag 'CoContra_Child3')",
    "Lines 141, 142: Expected error (tag 'CoContra_Child5')",
    "Lines 195, 196: Expected error (tag 'ContraToContraToContra_WithTA')"
  ],
  "generics_variance_inference.py": [
    "Line 26: Unexpected errors ['EXPECTED ClassA[float, int, int] <: ClassA[float, int, float]']",
    "Line 29: Unexpected errors ['EXPECTED ClassA[int, float, float] <: ClassA[int, int, float]']",
    "Line 40: Unexpected errors ['EXPECTED ShouldBeCovariant1[int] <: ShouldBeCovariant1[float]']",
    "Line 48: Unexpected errors ['EXPECTED ShouldBeCovariant2[int] <: ShouldBeCovariant2[float]']",
    "Line 57: Unexpected errors ['EXPECTED ShouldBeCovariant3[int] <: ShouldBeCovariant3[float]']",
    "Line 66: Unexpected errors ['EXPECTED ShouldBeCovariant4[int] <: ShouldBeCovariant4[float]']",
    "Line 79: Unexpected errors ['EXPECTED ShouldBeCovariant5[int] <: ShouldBeCovariant5[float]']",
    "Line 150: Unexpected errors ['EXPECTED ShouldBeContravariant1[float] <: ShouldBeContravariant1[int]']",
    "Line 182: Unexpected errors ['EXPECTED ShouldBeCovariant6[int] <: ShouldBeCovariant6[float]']",
    "Line 193: Unexpected errors ['EXPECTED ShouldBeContravariant2[float] <: ShouldBeContravariant2[int]']"
  ],
  "historical_positional.py": [
    "Line 18: Expected 1 errors",
    "Line 26: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 43: Expected 1 errors"
  ],
  "literals_interactions.py": [
    "Line 50: Unexpected errors ['assert_type(IO[str], IO[bytes]) failed']",
    "Line 51: Unexpected errors ['assert_type(IO[str], IO[Any]) failed']",
    "Line 71: Unexpected errors ['EXPECTED Matrix[Literal[3], Literal[7]] <: Matrix[Literal[3], TypeVar[C]]']",
    "Line 72: Unexpected errors ['assert_type(Matrix[Literal[2], TypeVar[C]], Matrix[Literal[2], Literal[7]]) failed']",
    "Line 106: Unexpected errors [\"EXPECTED str <: Literal['ABORTED', 'MALFORMED']\"]"
  ],
  "literals_literalstring.py": [
    "Line 120: Expected 1 errors",
    "Line 48: Unexpected errors ['assert_type(str, LiteralString) failed']",
    "Line 52: Unexpected errors ['assert_type(str, LiteralString) failed']",
    "Line 57: Unexpected errors ['`LiteralString` has no attribute `__iadd__`']",
    "Line 58: Unexpected errors ['`LiteralString` has no attribute `__iadd__`']",
    "Line 63: Unexpected errors ['assert_type(str, LiteralString) failed']",
    "Line 68: Unexpected errors ['assert_type(Any, str) failed']",
    "Line 111: Unexpected errors [\"assert_type(str, Literal['hello']) failed\"]",
    "Line 116: Unexpected errors ['assert_type(str, LiteralString) failed']",
    "Line 130: Unexpected errors ['EXPECTED Container[str] <: Container[LiteralString]']",
    "Line 166: Unexpected errors ['assert_type(C, B) failed']",
    "Line 167: Unexpected errors ['assert_type(C, A) failed']"
  ],
  "literals_parameterizations.py": [
    "Line 46: Expected 1 errors",
    "Line 60: Expected 1 errors",
    "Line 33: Unexpected errors ['Invalid literal expression', 'Invalid literal expression', 'Invalid literal expression', 'Invalid literal expression']",
    "Line 35: Unexpected errors ['Invalid literal expression']"
  ],
  "literals_semantics.py": [],
  "namedtuples_define_class.py": [
    "Line 59: Expected 1 errors",
    "Line 79: Expected 1 errors"
  ],
  "namedtuples_define_functional.py": [
    "Line 14: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point1, type[tuple[Any, ...]]]']",
    "Line 15: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point1, type[tuple[Any, ...]]]']",
    "Line 19: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point2, type[tuple[Any, ...]]]']",
    "Line 20: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point2, type[tuple[Any, ...]]]']",
    "Line 24: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point3, type[tuple[Any, ...]]]']",
    "Line 25: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point3, type[tuple[Any, ...]]]']",
    "Line 29: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point4, type[tuple[Any, ...]]]']",
    "Line 30: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[Point4, type[tuple[Any, ...]]]']",
    "Line 57: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[NT4, type[tuple[Any, ...]]]']",
    "Line 64: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[NT5, type[tuple[Any, ...]]]']",
    "Line 65: Unexpected errors ['Expected a callable, got LegacyImplicitTypeAlias[NT5, type[tuple[Any, ...]]]']"
  ],
  "namedtuples_type_compat.py": [],
  "namedtuples_usage.py": [
    "Line 40: Expected 1 errors"
  ],
  "narrowing_typeguard.py": [
    "Line 102: Expected 1 errors",
    "Line 107: Expected 1 errors",
    "Line 17: Unexpected errors ['assert_type(tuple[?_TypeVar, ?_TypeVar], tuple[str, str]) failed']",
    "Line 32: Unexpected errors ['assert_type(set[?_TypeVar], set[int]) failed']",
    "Line 72: Unexpected errors ['EXPECTED type[A] <: A']",
    "Line 76: Unexpected errors ['EXPECTED type[A] <: A']",
    "Line 89: Unexpected errors ['assert_type(A, B) failed']",
    "Line 93: Unexpected errors ['assert_type(A, B) failed']"
  ],
  "narrowing_typeis.py": [
    "Line 105: Expected 1 errors",
    "Line 110: Expected 1 errors",
    "Line 195: Expected 1 errors",
    "Line 199: Expected 1 errors",
    "Line 15: Unexpected errors ['EXPECTED bool <: TypeIs[tuple[?_TypeVar, ?_TypeVar]]']",
    "Line 19: Unexpected errors ['assert_type(tuple[str, ...], tuple[str, str]) failed']",
    "Line 28: Unexpected errors ['EXPECTED bool <: TypeIs[Awaitable[Any]]']",
    "Line 35: Unexpected errors ['Expression is not awaitable']",
    "Line 38: Unexpected errors ['assert_type(Awaitable[int] | int, int) failed']",
    "Line 45: Unexpected errors ['EXPECTED bool <: TypeIs[int]']",
    "Line 49: Unexpected errors ['EXPECTED bool <: TypeIs[int]']",
    "Line 53: Unexpected errors ['EXPECTED bool <: TypeIs[int]']",
    "Line 56: Unexpected errors ['EXPECTED bool <: TypeIs[A]']",
    "Line 59: Unexpected errors ['EXPECTED bool <: TypeIs[?_TypeVar]']",
    "Line 72: Unexpected errors ['assert_type(object, int) failed']",
    "Line 75: Unexpected errors ['EXPECTED type[A] <: A']",
    "Line 76: Unexpected errors ['assert_type(object, int) failed']",
    "Line 79: Unexpected errors ['EXPECTED type[A] <: A']",
    "Line 80: Unexpected errors ['assert_type(object, int) failed']",
    "Line 84: Unexpected errors ['assert_type(object, int) failed']",
    "Line 88: Unexpected errors ['assert_type(object, int) failed']",
    "Line 92: Unexpected errors ['assert_type(object, B) failed']",
    "Line 96: Unexpected errors ['assert_type(object, B) failed']",
    "Line 106: Unexpected errors ['EXPECTED Literal[False] <: TypeIs[int]']",
    "Line 111: Unexpected errors ['EXPECTED Literal[False] <: TypeIs[int]']",
    "Line 128: Unexpected errors ['EXPECTED bool <: TypeIs[int]']",
    "Line 163: Unexpected errors ['EXPECTED bool <: TypeIs[int]']",
    "Line 183: Unexpected errors ['EXPECTED bool <: TypeIs[int]']",
    "Line 187: Unexpected errors ['EXPECTED bool <: TypeIs[bool]']",
    "Line 196: Unexpected errors ['EXPECTED bool <: TypeIs[str]']",
    "Line 200: Unexpected errors ['EXPECTED bool <: TypeIs[list[int]]']"
  ],
  "overloads_basic.py": [],
  "protocols_class_objects.py": [
    "Line 29: Expected 1 errors",
    "Line 34: Expected 1 errors",
    "Line 104: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 107: Expected 1 errors",
    "Line 108: Expected 1 errors"
  ],
  "protocols_definition.py": [
    "Line 117: Expected 1 errors",
    "Line 157: Expected 1 errors",
    "Line 340: Expected 1 errors",
    "Line 341: Expected 1 errors",
    "Line 281: Unexpected errors ['EXPECTED Concrete5_Good2 <: Template5']"
  ],
  "protocols_explicit.py": [
    "Line 60: Expected 1 errors",
    "Line 90: Expected 1 errors",
    "Line 110: Expected 1 errors",
    "Line 135: Expected 1 errors",
    "Line 165: Expected 1 errors",
    "Line 157: Unexpected errors ['Class member `method1` overrides parent class `Proto7` in an inconsistent manner']"
  ],
  "protocols_generic.py": [
    "Line 87: Unexpected errors ['TODO: Expr::attr_infer attribute base undefined for type: ?_TypeVar (trying to access get_parent)']",
    "Line 144: Unexpected errors ['EXPECTED ConcreteHasProperty1 <: HasPropertyProto']",
    "Line 145: Unexpected errors ['EXPECTED ConcreteHasProperty2 <: HasPropertyProto']"
  ],
  "protocols_merging.py": [
    "Line 82: Expected 1 errors"
  ],
  "protocols_modules.py": [
    "Line 25: Unexpected errors ['EXPECTED Module[_protocols_modules1] <: Options1']"
  ],
  "protocols_recursive.py": [
    "Line 80: Unexpected errors ['EXPECTED ImplB <: ProtoA[Never, @_]']",
    "Line 81: Unexpected errors ['assert_type(Any, list[int]) failed']"
  ],
  "protocols_runtime_checkable.py": [
    "Line 23: Expected 1 errors",
    "Line 55: Expected 1 errors",
    "Line 61: Expected 1 errors",
    "Line 88: Expected 1 errors",
    "Line 92: Expected 1 errors",
    "Line 96: Expected 1 errors"
  ],
  "protocols_self.py": [
    "Line 32: Unexpected errors ['EXPECTED One <: Copyable']",
    "Line 33: Unexpected errors ['EXPECTED Other <: Copyable']",
    "Line 72: Unexpected errors ['EXPECTED C2[str] <: P2Parent[str]']",
    "Line 73: Unexpected errors ['EXPECTED C2[str] <: P2Child[str]']"
  ],
  "protocols_subtyping.py": [
    "Line 16: Expected 1 errors"
  ],
  "protocols_variance.py": [
    "Line 21: Expected 1 errors",
    "Line 40: Expected 1 errors",
    "Line 56: Expected 1 errors",
    "Line 61: Expected 1 errors",
    "Line 66: Expected 1 errors",
    "Line 71: Expected 1 errors",
    "Line 104: Expected 1 errors"
  ],
  "qualifiers_annotated.py": [
    "Line 47: Expected 1 errors",
    "Line 48: Expected 1 errors",
    "Line 49: Expected 1 errors",
    "Line 53: Expected 1 errors",
    "Line 64: Expected 1 errors",
    "Line 76: Expected 1 errors",
    "Line 77: Expected 1 errors",
    "Line 84: Expected 1 errors",
    "Line 85: Expected 1 errors",
    "Line 92: Expected 1 errors",
    "Line 93: Expected 1 errors",
    "Line 81: Unexpected errors ['Expected a callable, got type[?_TypeVar]']",
    "Line 98: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `ClassVar[int]`']",
    "Line 100: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `Final[int]`']",
    "Line 110: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `Required[int]`']",
    "Line 112: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `NotRequired[int]`']"
  ],
  "qualifiers_final_annotation.py": [
    "Line 16: Expected 1 errors",
    "Line 34: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 54: Expected 1 errors",
    "Line 65: Expected 1 errors",
    "Line 71: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 94: Expected 1 errors",
    "Line 107: Expected 1 errors",
    "Line 108: Expected 1 errors",
    "Line 121: Expected 1 errors",
    "Line 141: Expected 1 errors",
    "Line 147: Expected 1 errors",
    "Line 149: Expected 1 errors",
    "Line 152: Expected 1 errors",
    "Line 155: Expected 1 errors",
    "Line 96: Unexpected errors ['Class member `__private` overrides parent class `ClassC` in an inconsistent manner']",
    "Line 131: Unexpected errors ['Expected first item to be a string literal', 'Expected first item to be a string literal']",
    "Line 133: Unexpected errors ['Unexpected keyword argument `x`', 'Unexpected keyword argument `y`']",
    "Line 139: Unexpected errors ['TODO: StmtGlobal - Bindings::stmt']"
  ],
  "qualifiers_final_decorator.py": [
    "Line 21: Expected 1 errors",
    "Line 56: Expected 1 errors",
    "Lines 59, 60: Expected error (tag 'method2')",
    "Lines 63, 64: Expected error (tag 'method3')",
    "Lines 67, 75: Expected error (tag 'method4')",
    "Lines 80, 89: Expected error (tag 'Derived3')",
    "Lines 84, 85, 86: Expected error (tag 'Derived3-2')",
    "Lines 94, 102: Expected error (tag 'Derived4')",
    "Lines 125, 126: Expected error (tag 'func')"
  ],
  "specialtypes_any.py": [
    "Line 87: Unexpected errors ['Object of class `ClassA` has no attribute `method2`']",
    "Line 88: Unexpected errors ['Class `ClassA` has no class attribute `method3`']"
  ],
  "specialtypes_never.py": [
    "Line 32: Unexpected errors [\"EXPECTED Literal['whatever works'] <: int\"]"
  ],
  "specialtypes_none.py": [
    "Line 39: Unexpected errors ['EXPECTED type[object] <: type[None]']",
    "Line 40: Unexpected errors ['EXPECTED type <: type[None]']"
  ],
  "specialtypes_promotions.py": [],
  "specialtypes_type.py": [
    "Line 70: Expected 1 errors",
    "Line 39: Unexpected errors ['Expected a callable, got type[?_TypeVar]']",
    "Line 51: Unexpected errors ['Expected a callable, got type[BasicUser | ProUser]']",
    "Line 84: Unexpected errors ['assert_type(type, type[Any]) failed']",
    "Line 99: Unexpected errors ['Object of class `type` has no attribute `unknown`']",
    "Line 100: Unexpected errors ['Object of class `type` has no attribute `unknown`']",
    "Line 102: Unexpected errors ['assert_type(Any, tuple[type, ...]) failed']",
    "Line 106: Unexpected errors ['assert_type(Any, tuple[type, ...]) failed', 'TODO: Expr::attr_infer attribute base undefined for type: Type (trying to access __mro__)']",
    "Line 107: Unexpected errors ['TODO: Expr::attr_infer attribute base undefined for type: Type (trying to access unknown)']",
    "Line 108: Unexpected errors ['TODO: Expr::attr_infer attribute base undefined for type: Type (trying to access unknown)']",
    "Line 110: Unexpected errors ['assert_type(Any, tuple[type, ...]) failed']",
    "Line 137: Unexpected errors ['assert_type(Type, type[Any]) failed']",
    "Line 139: Unexpected errors ['assert_type(type, type[Any]) failed']",
    "Line 152: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[TA7, type[type[TypeVar[T]]]]\"]",
    "Line 156: Unexpected errors [\"Can't apply arguments to non-class, got LegacyExplicitTypeAlias[TA8, type[type[TypeVar[T]]]]\"]",
    "Line 160: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 161: Unexpected errors ['assert_type(Any, int) failed']",
    "Line 165: Unexpected errors ['EXPECTED type <: (...) -> Any']",
    "Line 166: Unexpected errors ['EXPECTED type <: (int, int) -> int']",
    "Line 169: Unexpected errors ['EXPECTED type <: type[int]']",
    "Line 170: Unexpected errors ['EXPECTED type <: type[Any]']",
    "Line 175: Unexpected errors ['EXPECTED type <: type[?_TypeVar]']"
  ],
  "tuples_type_compat.py": [
    "Line 59: Unexpected errors ['EXPECTED tuple[Any] <: tuple[int, int]']",
    "Line 74: Unexpected errors ['assert_type(tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int], tuple[int]) failed']",
    "Line 78: Unexpected errors ['assert_type(tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int], tuple[int, int] | tuple[str, str]) failed']",
    "Line 82: Unexpected errors ['assert_type(tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int], tuple[int, str, int]) failed']",
    "Line 93: Unexpected errors ['Cannot unpack tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int] (of size 2) into 1 value']",
    "Line 95: Unexpected errors ['assert_type(tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int], tuple[int]) failed']",
    "Line 97: Unexpected errors ['Cannot unpack tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int] (of size 1) into 2 values']",
    "Line 99: Unexpected errors ['assert_type(tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int], tuple[int, int] | tuple[str, str]) failed']",
    "Line 101: Unexpected errors ['Cannot unpack tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int] (of size 1) into 3 values', 'Cannot unpack tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int] (of size 2) into 3 values']",
    "Line 103: Unexpected errors ['assert_type(tuple[int] | tuple[str, str] | tuple[int, *tuple[str, ...], int], tuple[int, str, int]) failed']",
    "Line 115: Unexpected errors ['assert_type(tuple[int | str, int | str], tuple[int | str, str]) failed']",
    "Line 117: Unexpected errors ['assert_type(tuple[int | str, int | str], tuple[int | str, int]) failed']",
    "Line 139: Unexpected errors ['assert_type(Sequence[int | tuple[str, ...]], Sequence[int | str]) failed']"
  ],
  "tuples_type_form.py": [
    "Line 43: Expected 1 errors",
    "Line 44: Expected 1 errors"
  ],
  "tuples_unpacked.py": [],
  "typeddicts_alt_syntax.py": [],
  "typeddicts_class_syntax.py": [
    "Line 33: Expected 1 errors",
    "Line 38: Expected 1 errors",
    "Line 49: Expected 1 errors",
    "Line 34: Unexpected errors ['TypedDict item `method2` may not be initialized.']",
    "Line 39: Unexpected errors ['TypedDict item `method3` may not be initialized.']"
  ],
  "typeddicts_final.py": [],
  "typeddicts_inheritance.py": [
    "Line 65: Expected 1 errors"
  ],
  "typeddicts_operations.py": [
    "Line 60: Unexpected errors ['assert_type(object | None, str | None) failed']",
    "Line 64: Unexpected errors ['TODO: StmtDelete - Bindings::stmt']"
  ],
  "typeddicts_readonly.py": [
    "Line 61: Expected 1 errors",
    "Line 56: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `NotRequired[ReadOnly[int]]`']"
  ],
  "typeddicts_readonly_consistency.py": [
    "Line 38: Expected 1 errors",
    "Line 81: Expected 1 errors",
    "Line 79: Unexpected errors ['EXPECTED TypedDict[C2] <: TypedDict[A2]']"
  ],
  "typeddicts_readonly_inheritance.py": [
    "Line 94: Expected 1 errors",
    "Line 98: Expected 1 errors",
    "Line 106: Expected 1 errors",
    "Line 119: Expected 1 errors",
    "Line 132: Expected 1 errors",
    "Line 49: Unexpected errors ['Class member `albums` overrides parent class `AlbumCollection` in an inconsistent manner']",
    "Line 76: Unexpected errors ['Class member `ident` overrides parent class `OptionalIdent` in an inconsistent manner']"
  ],
  "typeddicts_readonly_kwargs.py": [],
  "typeddicts_readonly_update.py": [
    "Line 34: Unexpected errors ['Object of class `Mapping` has no attribute `update`']"
  ],
  "typeddicts_required.py": [
    "Line 12: Expected 1 errors",
    "Line 19: Expected 1 errors",
    "Line 62: Expected 1 errors",
    "Line 63: Expected 1 errors",
    "Line 68: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `Required[int]`']",
    "Line 70: Unexpected errors ['TODO: Answers::apply_special_form cannot handle `Required[Annotated[int, \"\"]]`']",
    "Line 74: Unexpected errors [\"untype, got Literal['RecursiveMovie']\"]"
  ],
  "typeddicts_type_consistency.py": [
    "Line 21: Expected 1 errors",
    "Line 91: Unexpected errors ['EXPECTED object | @_ <: str']",
    "Line 92: Unexpected errors ['EXPECTED object | @_ <: int']",
    "Line 97: Unexpected errors ['EXPECTED object | None <: str | None']",
    "Line 103: Unexpected errors ['EXPECTED object | @_ <: int']",
    "Line 105: Unexpected errors ['EXPECTED object | @_ <: int | str']",
    "Line 151: Unexpected errors [\"EXPECTED dict[str, int] <: Literal[''] | TypedDict[Inner3]\"]"
  ],
  "typeddicts_usage.py": [
    "Line 35: Expected 1 errors",
    "Line 40: Expected 1 errors"
  ]
}